package edu.thn.ciom.pojo;

import java.util.ArrayList;
import java.util.List;

public class DaohangPojoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DaohangPojoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJcdaohangidIsNull() {
            addCriterion("jcdaohangId is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidIsNotNull() {
            addCriterion("jcdaohangId is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidEqualTo(Integer value) {
            addCriterion("jcdaohangId =", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidNotEqualTo(Integer value) {
            addCriterion("jcdaohangId <>", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidGreaterThan(Integer value) {
            addCriterion("jcdaohangId >", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidGreaterThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangId >=", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidLessThan(Integer value) {
            addCriterion("jcdaohangId <", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidLessThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangId <=", value, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidIn(List<Integer> values) {
            addCriterion("jcdaohangId in", values, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidNotIn(List<Integer> values) {
            addCriterion("jcdaohangId not in", values, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangId between", value1, value2, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangidNotBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangId not between", value1, value2, "jcdaohangid");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameIsNull() {
            addCriterion("jcdaohangName is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameIsNotNull() {
            addCriterion("jcdaohangName is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameEqualTo(String value) {
            addCriterion("jcdaohangName =", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameNotEqualTo(String value) {
            addCriterion("jcdaohangName <>", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameGreaterThan(String value) {
            addCriterion("jcdaohangName >", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameGreaterThanOrEqualTo(String value) {
            addCriterion("jcdaohangName >=", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameLessThan(String value) {
            addCriterion("jcdaohangName <", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameLessThanOrEqualTo(String value) {
            addCriterion("jcdaohangName <=", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameLike(String value) {
            addCriterion("jcdaohangName like", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameNotLike(String value) {
            addCriterion("jcdaohangName not like", value, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameIn(List<String> values) {
            addCriterion("jcdaohangName in", values, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameNotIn(List<String> values) {
            addCriterion("jcdaohangName not in", values, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameBetween(String value1, String value2) {
            addCriterion("jcdaohangName between", value1, value2, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangnameNotBetween(String value1, String value2) {
            addCriterion("jcdaohangName not between", value1, value2, "jcdaohangname");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongIsNull() {
            addCriterion("jcdaohangNeirong is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongIsNotNull() {
            addCriterion("jcdaohangNeirong is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongEqualTo(String value) {
            addCriterion("jcdaohangNeirong =", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongNotEqualTo(String value) {
            addCriterion("jcdaohangNeirong <>", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongGreaterThan(String value) {
            addCriterion("jcdaohangNeirong >", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongGreaterThanOrEqualTo(String value) {
            addCriterion("jcdaohangNeirong >=", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongLessThan(String value) {
            addCriterion("jcdaohangNeirong <", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongLessThanOrEqualTo(String value) {
            addCriterion("jcdaohangNeirong <=", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongLike(String value) {
            addCriterion("jcdaohangNeirong like", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongNotLike(String value) {
            addCriterion("jcdaohangNeirong not like", value, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongIn(List<String> values) {
            addCriterion("jcdaohangNeirong in", values, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongNotIn(List<String> values) {
            addCriterion("jcdaohangNeirong not in", values, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongBetween(String value1, String value2) {
            addCriterion("jcdaohangNeirong between", value1, value2, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangneirongNotBetween(String value1, String value2) {
            addCriterion("jcdaohangNeirong not between", value1, value2, "jcdaohangneirong");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkIsNull() {
            addCriterion("jcdaohangMark is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkIsNotNull() {
            addCriterion("jcdaohangMark is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkEqualTo(String value) {
            addCriterion("jcdaohangMark =", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkNotEqualTo(String value) {
            addCriterion("jcdaohangMark <>", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkGreaterThan(String value) {
            addCriterion("jcdaohangMark >", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkGreaterThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark >=", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkLessThan(String value) {
            addCriterion("jcdaohangMark <", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkLessThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark <=", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkLike(String value) {
            addCriterion("jcdaohangMark like", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkNotLike(String value) {
            addCriterion("jcdaohangMark not like", value, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkIn(List<String> values) {
            addCriterion("jcdaohangMark in", values, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkNotIn(List<String> values) {
            addCriterion("jcdaohangMark not in", values, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkBetween(String value1, String value2) {
            addCriterion("jcdaohangMark between", value1, value2, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmarkNotBetween(String value1, String value2) {
            addCriterion("jcdaohangMark not between", value1, value2, "jcdaohangmark");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1IsNull() {
            addCriterion("jcdaohangMark1 is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1IsNotNull() {
            addCriterion("jcdaohangMark1 is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1EqualTo(String value) {
            addCriterion("jcdaohangMark1 =", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1NotEqualTo(String value) {
            addCriterion("jcdaohangMark1 <>", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1GreaterThan(String value) {
            addCriterion("jcdaohangMark1 >", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1GreaterThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark1 >=", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1LessThan(String value) {
            addCriterion("jcdaohangMark1 <", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1LessThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark1 <=", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1Like(String value) {
            addCriterion("jcdaohangMark1 like", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1NotLike(String value) {
            addCriterion("jcdaohangMark1 not like", value, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1In(List<String> values) {
            addCriterion("jcdaohangMark1 in", values, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1NotIn(List<String> values) {
            addCriterion("jcdaohangMark1 not in", values, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1Between(String value1, String value2) {
            addCriterion("jcdaohangMark1 between", value1, value2, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark1NotBetween(String value1, String value2) {
            addCriterion("jcdaohangMark1 not between", value1, value2, "jcdaohangmark1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2IsNull() {
            addCriterion("jcdaohangMark2 is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2IsNotNull() {
            addCriterion("jcdaohangMark2 is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2EqualTo(String value) {
            addCriterion("jcdaohangMark2 =", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2NotEqualTo(String value) {
            addCriterion("jcdaohangMark2 <>", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2GreaterThan(String value) {
            addCriterion("jcdaohangMark2 >", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2GreaterThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark2 >=", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2LessThan(String value) {
            addCriterion("jcdaohangMark2 <", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2LessThanOrEqualTo(String value) {
            addCriterion("jcdaohangMark2 <=", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2Like(String value) {
            addCriterion("jcdaohangMark2 like", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2NotLike(String value) {
            addCriterion("jcdaohangMark2 not like", value, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2In(List<String> values) {
            addCriterion("jcdaohangMark2 in", values, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2NotIn(List<String> values) {
            addCriterion("jcdaohangMark2 not in", values, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2Between(String value1, String value2) {
            addCriterion("jcdaohangMark2 between", value1, value2, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangmark2NotBetween(String value1, String value2) {
            addCriterion("jcdaohangMark2 not between", value1, value2, "jcdaohangmark2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuIsNull() {
            addCriterion("jcdaohangPaixu is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuIsNotNull() {
            addCriterion("jcdaohangPaixu is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuEqualTo(Integer value) {
            addCriterion("jcdaohangPaixu =", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuNotEqualTo(Integer value) {
            addCriterion("jcdaohangPaixu <>", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuGreaterThan(Integer value) {
            addCriterion("jcdaohangPaixu >", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuGreaterThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangPaixu >=", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuLessThan(Integer value) {
            addCriterion("jcdaohangPaixu <", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuLessThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangPaixu <=", value, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuIn(List<Integer> values) {
            addCriterion("jcdaohangPaixu in", values, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuNotIn(List<Integer> values) {
            addCriterion("jcdaohangPaixu not in", values, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangPaixu between", value1, value2, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangpaixuNotBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangPaixu not between", value1, value2, "jcdaohangpaixu");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeIsNull() {
            addCriterion("jcdaohangType is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeIsNotNull() {
            addCriterion("jcdaohangType is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeEqualTo(Integer value) {
            addCriterion("jcdaohangType =", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeNotEqualTo(Integer value) {
            addCriterion("jcdaohangType <>", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeGreaterThan(Integer value) {
            addCriterion("jcdaohangType >", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType >=", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeLessThan(Integer value) {
            addCriterion("jcdaohangType <", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeLessThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType <=", value, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeIn(List<Integer> values) {
            addCriterion("jcdaohangType in", values, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeNotIn(List<Integer> values) {
            addCriterion("jcdaohangType not in", values, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangType between", value1, value2, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangType not between", value1, value2, "jcdaohangtype");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1IsNull() {
            addCriterion("jcdaohangType1 is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1IsNotNull() {
            addCriterion("jcdaohangType1 is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1EqualTo(Integer value) {
            addCriterion("jcdaohangType1 =", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1NotEqualTo(Integer value) {
            addCriterion("jcdaohangType1 <>", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1GreaterThan(Integer value) {
            addCriterion("jcdaohangType1 >", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1GreaterThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType1 >=", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1LessThan(Integer value) {
            addCriterion("jcdaohangType1 <", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1LessThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType1 <=", value, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1In(List<Integer> values) {
            addCriterion("jcdaohangType1 in", values, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1NotIn(List<Integer> values) {
            addCriterion("jcdaohangType1 not in", values, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1Between(Integer value1, Integer value2) {
            addCriterion("jcdaohangType1 between", value1, value2, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype1NotBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangType1 not between", value1, value2, "jcdaohangtype1");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2IsNull() {
            addCriterion("jcdaohangType2 is null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2IsNotNull() {
            addCriterion("jcdaohangType2 is not null");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2EqualTo(Integer value) {
            addCriterion("jcdaohangType2 =", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2NotEqualTo(Integer value) {
            addCriterion("jcdaohangType2 <>", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2GreaterThan(Integer value) {
            addCriterion("jcdaohangType2 >", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2GreaterThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType2 >=", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2LessThan(Integer value) {
            addCriterion("jcdaohangType2 <", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2LessThanOrEqualTo(Integer value) {
            addCriterion("jcdaohangType2 <=", value, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2In(List<Integer> values) {
            addCriterion("jcdaohangType2 in", values, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2NotIn(List<Integer> values) {
            addCriterion("jcdaohangType2 not in", values, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2Between(Integer value1, Integer value2) {
            addCriterion("jcdaohangType2 between", value1, value2, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcdaohangtype2NotBetween(Integer value1, Integer value2) {
            addCriterion("jcdaohangType2 not between", value1, value2, "jcdaohangtype2");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidIsNull() {
            addCriterion("jcbiaotiId is null");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidIsNotNull() {
            addCriterion("jcbiaotiId is not null");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidEqualTo(Integer value) {
            addCriterion("jcbiaotiId =", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidNotEqualTo(Integer value) {
            addCriterion("jcbiaotiId <>", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidGreaterThan(Integer value) {
            addCriterion("jcbiaotiId >", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("jcbiaotiId >=", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidLessThan(Integer value) {
            addCriterion("jcbiaotiId <", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidLessThanOrEqualTo(Integer value) {
            addCriterion("jcbiaotiId <=", value, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidIn(List<Integer> values) {
            addCriterion("jcbiaotiId in", values, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidNotIn(List<Integer> values) {
            addCriterion("jcbiaotiId not in", values, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidBetween(Integer value1, Integer value2) {
            addCriterion("jcbiaotiId between", value1, value2, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotiidNotBetween(Integer value1, Integer value2) {
            addCriterion("jcbiaotiId not between", value1, value2, "jcbiaotiid");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameIsNull() {
            addCriterion("jcbiaotiName is null");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameIsNotNull() {
            addCriterion("jcbiaotiName is not null");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameEqualTo(String value) {
            addCriterion("jcbiaotiName =", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameNotEqualTo(String value) {
            addCriterion("jcbiaotiName <>", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameGreaterThan(String value) {
            addCriterion("jcbiaotiName >", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameGreaterThanOrEqualTo(String value) {
            addCriterion("jcbiaotiName >=", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameLessThan(String value) {
            addCriterion("jcbiaotiName <", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameLessThanOrEqualTo(String value) {
            addCriterion("jcbiaotiName <=", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameLike(String value) {
            addCriterion("jcbiaotiName like", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameNotLike(String value) {
            addCriterion("jcbiaotiName not like", value, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameIn(List<String> values) {
            addCriterion("jcbiaotiName in", values, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameNotIn(List<String> values) {
            addCriterion("jcbiaotiName not in", values, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameBetween(String value1, String value2) {
            addCriterion("jcbiaotiName between", value1, value2, "jcbiaotiname");
            return (Criteria) this;
        }

        public Criteria andJcbiaotinameNotBetween(String value1, String value2) {
            addCriterion("jcbiaotiName not between", value1, value2, "jcbiaotiname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jcdaohang
     *
     * @mbg.generated do_not_delete_during_merge Thu May 20 10:15:44 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}