package edu.thn.ciom.pojo;

import java.io.Serializable;
import java.util.Date;

public class DuochuPojo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochumark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochumark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochumark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochumark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjduochudate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjduochudate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochuzong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochuzong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochuzong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjduochudouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjduochudouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjduochudouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochutype1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjduochutype2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjqitaId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjqitaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjqitaName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjqitaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjlaiyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjlaiyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjlaiyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjlaiyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochuimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjduochuimgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.shujuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.shujuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjxingtaiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjxingtaiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjxingtaiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjxingtainame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer bumenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String bumenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byumenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byumenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buzhiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buzhiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.roleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.roleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuzhiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuzhiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yhroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yhrolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuId
     *
     * @return the value of t_sjduochu.sjduochuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochuid() {
        return sjduochuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuid(Integer sjduochuid) {
        this.setSjduochuid(sjduochuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuId
     *
     * @param sjduochuid the value for t_sjduochu.sjduochuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuid(Integer sjduochuid) {
        this.sjduochuid = sjduochuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuName
     *
     * @return the value of t_sjduochu.sjduochuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochuname() {
        return sjduochuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuname(String sjduochuname) {
        this.setSjduochuname(sjduochuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuName
     *
     * @param sjduochuname the value for t_sjduochu.sjduochuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuname(String sjduochuname) {
        this.sjduochuname = sjduochuname == null ? null : sjduochuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark
     *
     * @return the value of t_sjduochu.sjduochuMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochumark() {
        return sjduochumark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochumark(String sjduochumark) {
        this.setSjduochumark(sjduochumark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark
     *
     * @param sjduochumark the value for t_sjduochu.sjduochuMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochumark(String sjduochumark) {
        this.sjduochumark = sjduochumark == null ? null : sjduochumark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark1
     *
     * @return the value of t_sjduochu.sjduochuMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochumark1() {
        return sjduochumark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochumark1(String sjduochumark1) {
        this.setSjduochumark1(sjduochumark1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark1
     *
     * @param sjduochumark1 the value for t_sjduochu.sjduochuMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochumark1(String sjduochumark1) {
        this.sjduochumark1 = sjduochumark1 == null ? null : sjduochumark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark2
     *
     * @return the value of t_sjduochu.sjduochuMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochumark2() {
        return sjduochumark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochumark2(String sjduochumark2) {
        this.setSjduochumark2(sjduochumark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark2
     *
     * @param sjduochumark2 the value for t_sjduochu.sjduochuMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochumark2(String sjduochumark2) {
        this.sjduochumark2 = sjduochumark2 == null ? null : sjduochumark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark3
     *
     * @return the value of t_sjduochu.sjduochuMark3
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochumark3() {
        return sjduochumark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochumark3(String sjduochumark3) {
        this.setSjduochumark3(sjduochumark3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark3
     *
     * @param sjduochumark3 the value for t_sjduochu.sjduochuMark3
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochumark3(String sjduochumark3) {
        this.sjduochumark3 = sjduochumark3 == null ? null : sjduochumark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDate
     *
     * @return the value of t_sjduochu.sjduochuDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjduochudate() {
        return sjduochudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochudate(Date sjduochudate) {
        this.setSjduochudate(sjduochudate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDate
     *
     * @param sjduochudate the value for t_sjduochu.sjduochuDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochudate(Date sjduochudate) {
        this.sjduochudate = sjduochudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDate1
     *
     * @return the value of t_sjduochu.sjduochuDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjduochudate1() {
        return sjduochudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochudate1(Date sjduochudate1) {
        this.setSjduochudate1(sjduochudate1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDate1
     *
     * @param sjduochudate1 the value for t_sjduochu.sjduochuDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochudate1(Date sjduochudate1) {
        this.sjduochudate1 = sjduochudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong
     *
     * @return the value of t_sjduochu.sjduochuZong
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochuzong() {
        return sjduochuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuzong(Integer sjduochuzong) {
        this.setSjduochuzong(sjduochuzong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong
     *
     * @param sjduochuzong the value for t_sjduochu.sjduochuZong
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuzong(Integer sjduochuzong) {
        this.sjduochuzong = sjduochuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong1
     *
     * @return the value of t_sjduochu.sjduochuZong1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochuzong1() {
        return sjduochuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuzong1(Integer sjduochuzong1) {
        this.setSjduochuzong1(sjduochuzong1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong1
     *
     * @param sjduochuzong1 the value for t_sjduochu.sjduochuZong1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuzong1(Integer sjduochuzong1) {
        this.sjduochuzong1 = sjduochuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong2
     *
     * @return the value of t_sjduochu.sjduochuZong2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochuzong2() {
        return sjduochuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuzong2(Integer sjduochuzong2) {
        this.setSjduochuzong2(sjduochuzong2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong2
     *
     * @param sjduochuzong2 the value for t_sjduochu.sjduochuZong2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuzong2(Integer sjduochuzong2) {
        this.sjduochuzong2 = sjduochuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble
     *
     * @return the value of t_sjduochu.sjduochuDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjduochudouble() {
        return sjduochudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochudouble(Double sjduochudouble) {
        this.setSjduochudouble(sjduochudouble);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble
     *
     * @param sjduochudouble the value for t_sjduochu.sjduochuDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochudouble(Double sjduochudouble) {
        this.sjduochudouble = sjduochudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble1
     *
     * @return the value of t_sjduochu.sjduochuDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjduochudouble1() {
        return sjduochudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochudouble1(Double sjduochudouble1) {
        this.setSjduochudouble1(sjduochudouble1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble1
     *
     * @param sjduochudouble1 the value for t_sjduochu.sjduochuDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochudouble1(Double sjduochudouble1) {
        this.sjduochudouble1 = sjduochudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble2
     *
     * @return the value of t_sjduochu.sjduochuDouble2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjduochudouble2() {
        return sjduochudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochudouble2(Double sjduochudouble2) {
        this.setSjduochudouble2(sjduochudouble2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble2
     *
     * @param sjduochudouble2 the value for t_sjduochu.sjduochuDouble2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochudouble2(Double sjduochudouble2) {
        this.sjduochudouble2 = sjduochudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType
     *
     * @return the value of t_sjduochu.sjduochuType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochutype() {
        return sjduochutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochutype(Integer sjduochutype) {
        this.setSjduochutype(sjduochutype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType
     *
     * @param sjduochutype the value for t_sjduochu.sjduochuType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochutype(Integer sjduochutype) {
        this.sjduochutype = sjduochutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType1
     *
     * @return the value of t_sjduochu.sjduochuType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochutype1() {
        return sjduochutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochutype1(Integer sjduochutype1) {
        this.setSjduochutype1(sjduochutype1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType1
     *
     * @param sjduochutype1 the value for t_sjduochu.sjduochuType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochutype1(Integer sjduochutype1) {
        this.sjduochutype1 = sjduochutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType2
     *
     * @return the value of t_sjduochu.sjduochuType2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjduochutype2() {
        return sjduochutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochutype2(Integer sjduochutype2) {
        this.setSjduochutype2(sjduochutype2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType2
     *
     * @param sjduochutype2 the value for t_sjduochu.sjduochuType2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochutype2(Integer sjduochutype2) {
        this.sjduochutype2 = sjduochutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjqitaId
     *
     * @return the value of t_sjduochu.sjqitaId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjqitaid() {
        return sjqitaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjqitaid(Integer sjqitaid) {
        this.setSjqitaid(sjqitaid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjqitaId
     *
     * @param sjqitaid the value for t_sjduochu.sjqitaId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjqitaid(Integer sjqitaid) {
        this.sjqitaid = sjqitaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjqitaName
     *
     * @return the value of t_sjduochu.sjqitaName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjqitaname() {
        return sjqitaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjqitaname(String sjqitaname) {
        this.setSjqitaname(sjqitaname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjqitaName
     *
     * @param sjqitaname the value for t_sjduochu.sjqitaName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjqitaname(String sjqitaname) {
        this.sjqitaname = sjqitaname == null ? null : sjqitaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjlaiyuanId
     *
     * @return the value of t_sjduochu.sjlaiyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjlaiyuanid() {
        return sjlaiyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjlaiyuanid(Integer sjlaiyuanid) {
        this.setSjlaiyuanid(sjlaiyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjlaiyuanId
     *
     * @param sjlaiyuanid the value for t_sjduochu.sjlaiyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjlaiyuanid(Integer sjlaiyuanid) {
        this.sjlaiyuanid = sjlaiyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjlaiyuanName
     *
     * @return the value of t_sjduochu.sjlaiyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjlaiyuanname() {
        return sjlaiyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjlaiyuanname(String sjlaiyuanname) {
        this.setSjlaiyuanname(sjlaiyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjlaiyuanName
     *
     * @param sjlaiyuanname the value for t_sjduochu.sjlaiyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjlaiyuanname(String sjlaiyuanname) {
        this.sjlaiyuanname = sjlaiyuanname == null ? null : sjlaiyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuImg
     *
     * @return the value of t_sjduochu.sjduochuImg
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochuimg() {
        return sjduochuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuimg(String sjduochuimg) {
        this.setSjduochuimg(sjduochuimg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuImg
     *
     * @param sjduochuimg the value for t_sjduochu.sjduochuImg
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuimg(String sjduochuimg) {
        this.sjduochuimg = sjduochuimg == null ? null : sjduochuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuImgName
     *
     * @return the value of t_sjduochu.sjduochuImgName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjduochuimgname() {
        return sjduochuimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjduochuimgname(String sjduochuimgname) {
        this.setSjduochuimgname(sjduochuimgname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuImgName
     *
     * @param sjduochuimgname the value for t_sjduochu.sjduochuImgName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjduochuimgname(String sjduochuimgname) {
        this.sjduochuimgname = sjduochuimgname == null ? null : sjduochuimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.shujuId
     *
     * @return the value of t_sjduochu.shujuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuid() {
        return shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withShujuid(Integer shujuid) {
        this.setShujuid(shujuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.shujuId
     *
     * @param shujuid the value for t_sjduochu.shujuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuid(Integer shujuid) {
        this.shujuid = shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.shujuName
     *
     * @return the value of t_sjduochu.shujuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujuname() {
        return shujuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withShujuname(String shujuname) {
        this.setShujuname(shujuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.shujuName
     *
     * @param shujuname the value for t_sjduochu.shujuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuname(String shujuname) {
        this.shujuname = shujuname == null ? null : shujuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjleixingId
     *
     * @return the value of t_sjduochu.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingid() {
        return sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjleixingid(Integer sjleixingid) {
        this.setSjleixingid(sjleixingid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjleixingId
     *
     * @param sjleixingid the value for t_sjduochu.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingid(Integer sjleixingid) {
        this.sjleixingid = sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjleixingName
     *
     * @return the value of t_sjduochu.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingname() {
        return sjleixingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjleixingname(String sjleixingname) {
        this.setSjleixingname(sjleixingname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjleixingName
     *
     * @param sjleixingname the value for t_sjduochu.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingname(String sjleixingname) {
        this.sjleixingname = sjleixingname == null ? null : sjleixingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjxingtaiId
     *
     * @return the value of t_sjduochu.sjxingtaiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjxingtaiid() {
        return sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjxingtaiid(Integer sjxingtaiid) {
        this.setSjxingtaiid(sjxingtaiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjxingtaiId
     *
     * @param sjxingtaiid the value for t_sjduochu.sjxingtaiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtaiid(Integer sjxingtaiid) {
        this.sjxingtaiid = sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjxingtaiName
     *
     * @return the value of t_sjduochu.sjxingtaiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjxingtainame() {
        return sjxingtainame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withSjxingtainame(String sjxingtainame) {
        this.setSjxingtainame(sjxingtainame);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjxingtaiName
     *
     * @param sjxingtainame the value for t_sjduochu.sjxingtaiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtainame(String sjxingtainame) {
        this.sjxingtainame = sjxingtainame == null ? null : sjxingtainame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.userId
     *
     * @return the value of t_sjduochu.userId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withUserid(Integer userid) {
        this.setUserid(userid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.userId
     *
     * @param userid the value for t_sjduochu.userId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.userName
     *
     * @return the value of t_sjduochu.userName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.userName
     *
     * @param username the value for t_sjduochu.userName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.bumenId
     *
     * @return the value of t_sjduochu.bumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBumenid(Integer bumenid) {
        this.setBumenid(bumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.bumenId
     *
     * @param bumenid the value for t_sjduochu.bumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.bumenName
     *
     * @return the value of t_sjduochu.bumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBumenname() {
        return bumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBumenname(String bumenname) {
        this.setBumenname(bumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.bumenName
     *
     * @param bumenname the value for t_sjduochu.bumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenname(String bumenname) {
        this.bumenname = bumenname == null ? null : bumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buyuanId
     *
     * @return the value of t_sjduochu.buyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuyuanid() {
        return buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBuyuanid(Integer buyuanid) {
        this.setBuyuanid(buyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buyuanId
     *
     * @param buyuanid the value for t_sjduochu.buyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanid(Integer buyuanid) {
        this.buyuanid = buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buyuanName
     *
     * @return the value of t_sjduochu.buyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuyuanname() {
        return buyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBuyuanname(String buyuanname) {
        this.setBuyuanname(buyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buyuanName
     *
     * @param buyuanname the value for t_sjduochu.buyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanname(String buyuanname) {
        this.buyuanname = buyuanname == null ? null : buyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yonghuId
     *
     * @return the value of t_sjduochu.yonghuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuid() {
        return yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withYonghuid(Integer yonghuid) {
        this.setYonghuid(yonghuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yonghuId
     *
     * @param yonghuid the value for t_sjduochu.yonghuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuid(Integer yonghuid) {
        this.yonghuid = yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yonghuName
     *
     * @return the value of t_sjduochu.yonghuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuname() {
        return yonghuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withYonghuname(String yonghuname) {
        this.setYonghuname(yonghuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yonghuName
     *
     * @param yonghuname the value for t_sjduochu.yonghuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuname(String yonghuname) {
        this.yonghuname = yonghuname == null ? null : yonghuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byumenId
     *
     * @return the value of t_sjduochu.byumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByumenid() {
        return byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByumenid(Integer byumenid) {
        this.setByumenid(byumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byumenId
     *
     * @param byumenid the value for t_sjduochu.byumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenid(Integer byumenid) {
        this.byumenid = byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byumenName
     *
     * @return the value of t_sjduochu.byumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByumenname() {
        return byumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByumenname(String byumenname) {
        this.setByumenname(byumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byumenName
     *
     * @param byumenname the value for t_sjduochu.byumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenname(String byumenname) {
        this.byumenname = byumenname == null ? null : byumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuyuanId
     *
     * @return the value of t_sjduochu.byuyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuyuanid() {
        return byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByuyuanid(Integer byuyuanid) {
        this.setByuyuanid(byuyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuyuanId
     *
     * @param byuyuanid the value for t_sjduochu.byuyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanid(Integer byuyuanid) {
        this.byuyuanid = byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuyuanName
     *
     * @return the value of t_sjduochu.byuyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuyuanname() {
        return byuyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByuyuanname(String byuyuanname) {
        this.setByuyuanname(byuyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuyuanName
     *
     * @param byuyuanname the value for t_sjduochu.byuyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanname(String byuyuanname) {
        this.byuyuanname = byuyuanname == null ? null : byuyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buzhiId
     *
     * @return the value of t_sjduochu.buzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuzhiid() {
        return buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBuzhiid(Integer buzhiid) {
        this.setBuzhiid(buzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buzhiId
     *
     * @param buzhiid the value for t_sjduochu.buzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiid(Integer buzhiid) {
        this.buzhiid = buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buzhiName
     *
     * @return the value of t_sjduochu.buzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuzhiname() {
        return buzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withBuzhiname(String buzhiname) {
        this.setBuzhiname(buzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buzhiName
     *
     * @param buzhiname the value for t_sjduochu.buzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiname(String buzhiname) {
        this.buzhiname = buzhiname == null ? null : buzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.roleId
     *
     * @return the value of t_sjduochu.roleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withRoleid(Integer roleid) {
        this.setRoleid(roleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.roleId
     *
     * @param roleid the value for t_sjduochu.roleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.roleName
     *
     * @return the value of t_sjduochu.roleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withRolename(String rolename) {
        this.setRolename(rolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.roleName
     *
     * @param rolename the value for t_sjduochu.roleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuzhiId
     *
     * @return the value of t_sjduochu.byuzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuzhiid() {
        return byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByuzhiid(Integer byuzhiid) {
        this.setByuzhiid(byuzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuzhiId
     *
     * @param byuzhiid the value for t_sjduochu.byuzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiid(Integer byuzhiid) {
        this.byuzhiid = byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuzhiName
     *
     * @return the value of t_sjduochu.byuzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuzhiname() {
        return byuzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withByuzhiname(String byuzhiname) {
        this.setByuzhiname(byuzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuzhiName
     *
     * @param byuzhiname the value for t_sjduochu.byuzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiname(String byuzhiname) {
        this.byuzhiname = byuzhiname == null ? null : byuzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yhroleId
     *
     * @return the value of t_sjduochu.yhroleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYhroleid() {
        return yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withYhroleid(Integer yhroleid) {
        this.setYhroleid(yhroleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yhroleId
     *
     * @param yhroleid the value for t_sjduochu.yhroleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhroleid(Integer yhroleid) {
        this.yhroleid = yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yhroleName
     *
     * @return the value of t_sjduochu.yhroleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYhrolename() {
        return yhrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public DuochuPojo withYhrolename(String yhrolename) {
        this.setYhrolename(yhrolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yhroleName
     *
     * @param yhrolename the value for t_sjduochu.yhroleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhrolename(String yhrolename) {
        this.yhrolename = yhrolename == null ? null : yhrolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sjduochuid=").append(sjduochuid);
        sb.append(", sjduochuname=").append(sjduochuname);
        sb.append(", sjduochumark=").append(sjduochumark);
        sb.append(", sjduochumark1=").append(sjduochumark1);
        sb.append(", sjduochumark2=").append(sjduochumark2);
        sb.append(", sjduochumark3=").append(sjduochumark3);
        sb.append(", sjduochudate=").append(sjduochudate);
        sb.append(", sjduochudate1=").append(sjduochudate1);
        sb.append(", sjduochuzong=").append(sjduochuzong);
        sb.append(", sjduochuzong1=").append(sjduochuzong1);
        sb.append(", sjduochuzong2=").append(sjduochuzong2);
        sb.append(", sjduochudouble=").append(sjduochudouble);
        sb.append(", sjduochudouble1=").append(sjduochudouble1);
        sb.append(", sjduochudouble2=").append(sjduochudouble2);
        sb.append(", sjduochutype=").append(sjduochutype);
        sb.append(", sjduochutype1=").append(sjduochutype1);
        sb.append(", sjduochutype2=").append(sjduochutype2);
        sb.append(", sjqitaid=").append(sjqitaid);
        sb.append(", sjqitaname=").append(sjqitaname);
        sb.append(", sjlaiyuanid=").append(sjlaiyuanid);
        sb.append(", sjlaiyuanname=").append(sjlaiyuanname);
        sb.append(", sjduochuimg=").append(sjduochuimg);
        sb.append(", sjduochuimgname=").append(sjduochuimgname);
        sb.append(", shujuid=").append(shujuid);
        sb.append(", shujuname=").append(shujuname);
        sb.append(", sjleixingid=").append(sjleixingid);
        sb.append(", sjleixingname=").append(sjleixingname);
        sb.append(", sjxingtaiid=").append(sjxingtaiid);
        sb.append(", sjxingtainame=").append(sjxingtainame);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", bumenid=").append(bumenid);
        sb.append(", bumenname=").append(bumenname);
        sb.append(", buyuanid=").append(buyuanid);
        sb.append(", buyuanname=").append(buyuanname);
        sb.append(", yonghuid=").append(yonghuid);
        sb.append(", yonghuname=").append(yonghuname);
        sb.append(", byumenid=").append(byumenid);
        sb.append(", byumenname=").append(byumenname);
        sb.append(", byuyuanid=").append(byuyuanid);
        sb.append(", byuyuanname=").append(byuyuanname);
        sb.append(", buzhiid=").append(buzhiid);
        sb.append(", buzhiname=").append(buzhiname);
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", byuzhiid=").append(byuzhiid);
        sb.append(", byuzhiname=").append(byuzhiname);
        sb.append(", yhroleid=").append(yhroleid);
        sb.append(", yhrolename=").append(yhrolename);
        sb.append("]");
        return sb.toString();
    }
}