package edu.thn.ciom.pojo;

import java.io.Serializable;
import java.util.Date;

public class JianChuPojo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchumark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchumark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchumark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchumark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjjianchudate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjjianchudate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchuzong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchuzong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchuzong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjjianchudouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjjianchudouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjjianchudouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchutype1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjjianchutype2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjqitaId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjqitaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjqitaName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjqitaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjlaiyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjlaiyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjlaiyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjlaiyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchuimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjjianchuimgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.shujuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.shujuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjxingtaiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjxingtaiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjxingtaiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjxingtainame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer bumenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String bumenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byumenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byumenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuyuanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buzhiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buzhiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.roleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.roleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuzhiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuzhiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yhroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yhrolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuId
     *
     * @return the value of t_sjjianchu.sjjianchuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchuid() {
        return sjjianchuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuid(Integer sjjianchuid) {
        this.setSjjianchuid(sjjianchuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuId
     *
     * @param sjjianchuid the value for t_sjjianchu.sjjianchuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuid(Integer sjjianchuid) {
        this.sjjianchuid = sjjianchuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuName
     *
     * @return the value of t_sjjianchu.sjjianchuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchuname() {
        return sjjianchuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuname(String sjjianchuname) {
        this.setSjjianchuname(sjjianchuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuName
     *
     * @param sjjianchuname the value for t_sjjianchu.sjjianchuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuname(String sjjianchuname) {
        this.sjjianchuname = sjjianchuname == null ? null : sjjianchuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark
     *
     * @return the value of t_sjjianchu.sjjianchuMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchumark() {
        return sjjianchumark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchumark(String sjjianchumark) {
        this.setSjjianchumark(sjjianchumark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark
     *
     * @param sjjianchumark the value for t_sjjianchu.sjjianchuMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchumark(String sjjianchumark) {
        this.sjjianchumark = sjjianchumark == null ? null : sjjianchumark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark1
     *
     * @return the value of t_sjjianchu.sjjianchuMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchumark1() {
        return sjjianchumark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchumark1(String sjjianchumark1) {
        this.setSjjianchumark1(sjjianchumark1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark1
     *
     * @param sjjianchumark1 the value for t_sjjianchu.sjjianchuMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchumark1(String sjjianchumark1) {
        this.sjjianchumark1 = sjjianchumark1 == null ? null : sjjianchumark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark2
     *
     * @return the value of t_sjjianchu.sjjianchuMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchumark2() {
        return sjjianchumark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchumark2(String sjjianchumark2) {
        this.setSjjianchumark2(sjjianchumark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark2
     *
     * @param sjjianchumark2 the value for t_sjjianchu.sjjianchuMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchumark2(String sjjianchumark2) {
        this.sjjianchumark2 = sjjianchumark2 == null ? null : sjjianchumark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark3
     *
     * @return the value of t_sjjianchu.sjjianchuMark3
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchumark3() {
        return sjjianchumark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchumark3(String sjjianchumark3) {
        this.setSjjianchumark3(sjjianchumark3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark3
     *
     * @param sjjianchumark3 the value for t_sjjianchu.sjjianchuMark3
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchumark3(String sjjianchumark3) {
        this.sjjianchumark3 = sjjianchumark3 == null ? null : sjjianchumark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDate
     *
     * @return the value of t_sjjianchu.sjjianchuDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjjianchudate() {
        return sjjianchudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchudate(Date sjjianchudate) {
        this.setSjjianchudate(sjjianchudate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDate
     *
     * @param sjjianchudate the value for t_sjjianchu.sjjianchuDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchudate(Date sjjianchudate) {
        this.sjjianchudate = sjjianchudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDate1
     *
     * @return the value of t_sjjianchu.sjjianchuDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjjianchudate1() {
        return sjjianchudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchudate1(Date sjjianchudate1) {
        this.setSjjianchudate1(sjjianchudate1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDate1
     *
     * @param sjjianchudate1 the value for t_sjjianchu.sjjianchuDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchudate1(Date sjjianchudate1) {
        this.sjjianchudate1 = sjjianchudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong
     *
     * @return the value of t_sjjianchu.sjjianchuZong
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchuzong() {
        return sjjianchuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuzong(Integer sjjianchuzong) {
        this.setSjjianchuzong(sjjianchuzong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong
     *
     * @param sjjianchuzong the value for t_sjjianchu.sjjianchuZong
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuzong(Integer sjjianchuzong) {
        this.sjjianchuzong = sjjianchuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong1
     *
     * @return the value of t_sjjianchu.sjjianchuZong1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchuzong1() {
        return sjjianchuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuzong1(Integer sjjianchuzong1) {
        this.setSjjianchuzong1(sjjianchuzong1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong1
     *
     * @param sjjianchuzong1 the value for t_sjjianchu.sjjianchuZong1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuzong1(Integer sjjianchuzong1) {
        this.sjjianchuzong1 = sjjianchuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong2
     *
     * @return the value of t_sjjianchu.sjjianchuZong2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchuzong2() {
        return sjjianchuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuzong2(Integer sjjianchuzong2) {
        this.setSjjianchuzong2(sjjianchuzong2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong2
     *
     * @param sjjianchuzong2 the value for t_sjjianchu.sjjianchuZong2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuzong2(Integer sjjianchuzong2) {
        this.sjjianchuzong2 = sjjianchuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble
     *
     * @return the value of t_sjjianchu.sjjianchuDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjjianchudouble() {
        return sjjianchudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchudouble(Double sjjianchudouble) {
        this.setSjjianchudouble(sjjianchudouble);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble
     *
     * @param sjjianchudouble the value for t_sjjianchu.sjjianchuDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchudouble(Double sjjianchudouble) {
        this.sjjianchudouble = sjjianchudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble1
     *
     * @return the value of t_sjjianchu.sjjianchuDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjjianchudouble1() {
        return sjjianchudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchudouble1(Double sjjianchudouble1) {
        this.setSjjianchudouble1(sjjianchudouble1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble1
     *
     * @param sjjianchudouble1 the value for t_sjjianchu.sjjianchuDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchudouble1(Double sjjianchudouble1) {
        this.sjjianchudouble1 = sjjianchudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble2
     *
     * @return the value of t_sjjianchu.sjjianchuDouble2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjjianchudouble2() {
        return sjjianchudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchudouble2(Double sjjianchudouble2) {
        this.setSjjianchudouble2(sjjianchudouble2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble2
     *
     * @param sjjianchudouble2 the value for t_sjjianchu.sjjianchuDouble2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchudouble2(Double sjjianchudouble2) {
        this.sjjianchudouble2 = sjjianchudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType
     *
     * @return the value of t_sjjianchu.sjjianchuType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchutype() {
        return sjjianchutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchutype(Integer sjjianchutype) {
        this.setSjjianchutype(sjjianchutype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType
     *
     * @param sjjianchutype the value for t_sjjianchu.sjjianchuType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchutype(Integer sjjianchutype) {
        this.sjjianchutype = sjjianchutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType1
     *
     * @return the value of t_sjjianchu.sjjianchuType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchutype1() {
        return sjjianchutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchutype1(Integer sjjianchutype1) {
        this.setSjjianchutype1(sjjianchutype1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType1
     *
     * @param sjjianchutype1 the value for t_sjjianchu.sjjianchuType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchutype1(Integer sjjianchutype1) {
        this.sjjianchutype1 = sjjianchutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType2
     *
     * @return the value of t_sjjianchu.sjjianchuType2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjjianchutype2() {
        return sjjianchutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchutype2(Integer sjjianchutype2) {
        this.setSjjianchutype2(sjjianchutype2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType2
     *
     * @param sjjianchutype2 the value for t_sjjianchu.sjjianchuType2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchutype2(Integer sjjianchutype2) {
        this.sjjianchutype2 = sjjianchutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjqitaId
     *
     * @return the value of t_sjjianchu.sjqitaId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjqitaid() {
        return sjqitaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjqitaid(Integer sjqitaid) {
        this.setSjqitaid(sjqitaid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjqitaId
     *
     * @param sjqitaid the value for t_sjjianchu.sjqitaId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjqitaid(Integer sjqitaid) {
        this.sjqitaid = sjqitaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjqitaName
     *
     * @return the value of t_sjjianchu.sjqitaName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjqitaname() {
        return sjqitaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjqitaname(String sjqitaname) {
        this.setSjqitaname(sjqitaname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjqitaName
     *
     * @param sjqitaname the value for t_sjjianchu.sjqitaName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjqitaname(String sjqitaname) {
        this.sjqitaname = sjqitaname == null ? null : sjqitaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjlaiyuanId
     *
     * @return the value of t_sjjianchu.sjlaiyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjlaiyuanid() {
        return sjlaiyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjlaiyuanid(Integer sjlaiyuanid) {
        this.setSjlaiyuanid(sjlaiyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjlaiyuanId
     *
     * @param sjlaiyuanid the value for t_sjjianchu.sjlaiyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjlaiyuanid(Integer sjlaiyuanid) {
        this.sjlaiyuanid = sjlaiyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjlaiyuanName
     *
     * @return the value of t_sjjianchu.sjlaiyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjlaiyuanname() {
        return sjlaiyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjlaiyuanname(String sjlaiyuanname) {
        this.setSjlaiyuanname(sjlaiyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjlaiyuanName
     *
     * @param sjlaiyuanname the value for t_sjjianchu.sjlaiyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjlaiyuanname(String sjlaiyuanname) {
        this.sjlaiyuanname = sjlaiyuanname == null ? null : sjlaiyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuImg
     *
     * @return the value of t_sjjianchu.sjjianchuImg
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchuimg() {
        return sjjianchuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuimg(String sjjianchuimg) {
        this.setSjjianchuimg(sjjianchuimg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuImg
     *
     * @param sjjianchuimg the value for t_sjjianchu.sjjianchuImg
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuimg(String sjjianchuimg) {
        this.sjjianchuimg = sjjianchuimg == null ? null : sjjianchuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuImgName
     *
     * @return the value of t_sjjianchu.sjjianchuImgName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjjianchuimgname() {
        return sjjianchuimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjjianchuimgname(String sjjianchuimgname) {
        this.setSjjianchuimgname(sjjianchuimgname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuImgName
     *
     * @param sjjianchuimgname the value for t_sjjianchu.sjjianchuImgName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjjianchuimgname(String sjjianchuimgname) {
        this.sjjianchuimgname = sjjianchuimgname == null ? null : sjjianchuimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.shujuId
     *
     * @return the value of t_sjjianchu.shujuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuid() {
        return shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withShujuid(Integer shujuid) {
        this.setShujuid(shujuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.shujuId
     *
     * @param shujuid the value for t_sjjianchu.shujuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuid(Integer shujuid) {
        this.shujuid = shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.shujuName
     *
     * @return the value of t_sjjianchu.shujuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujuname() {
        return shujuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withShujuname(String shujuname) {
        this.setShujuname(shujuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.shujuName
     *
     * @param shujuname the value for t_sjjianchu.shujuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuname(String shujuname) {
        this.shujuname = shujuname == null ? null : shujuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjleixingId
     *
     * @return the value of t_sjjianchu.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingid() {
        return sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjleixingid(Integer sjleixingid) {
        this.setSjleixingid(sjleixingid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjleixingId
     *
     * @param sjleixingid the value for t_sjjianchu.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingid(Integer sjleixingid) {
        this.sjleixingid = sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjleixingName
     *
     * @return the value of t_sjjianchu.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingname() {
        return sjleixingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjleixingname(String sjleixingname) {
        this.setSjleixingname(sjleixingname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjleixingName
     *
     * @param sjleixingname the value for t_sjjianchu.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingname(String sjleixingname) {
        this.sjleixingname = sjleixingname == null ? null : sjleixingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjxingtaiId
     *
     * @return the value of t_sjjianchu.sjxingtaiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjxingtaiid() {
        return sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjxingtaiid(Integer sjxingtaiid) {
        this.setSjxingtaiid(sjxingtaiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjxingtaiId
     *
     * @param sjxingtaiid the value for t_sjjianchu.sjxingtaiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtaiid(Integer sjxingtaiid) {
        this.sjxingtaiid = sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjxingtaiName
     *
     * @return the value of t_sjjianchu.sjxingtaiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjxingtainame() {
        return sjxingtainame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withSjxingtainame(String sjxingtainame) {
        this.setSjxingtainame(sjxingtainame);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjxingtaiName
     *
     * @param sjxingtainame the value for t_sjjianchu.sjxingtaiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtainame(String sjxingtainame) {
        this.sjxingtainame = sjxingtainame == null ? null : sjxingtainame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.userId
     *
     * @return the value of t_sjjianchu.userId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withUserid(Integer userid) {
        this.setUserid(userid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.userId
     *
     * @param userid the value for t_sjjianchu.userId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.userName
     *
     * @return the value of t_sjjianchu.userName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.userName
     *
     * @param username the value for t_sjjianchu.userName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.bumenId
     *
     * @return the value of t_sjjianchu.bumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBumenid(Integer bumenid) {
        this.setBumenid(bumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.bumenId
     *
     * @param bumenid the value for t_sjjianchu.bumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.bumenName
     *
     * @return the value of t_sjjianchu.bumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBumenname() {
        return bumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBumenname(String bumenname) {
        this.setBumenname(bumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.bumenName
     *
     * @param bumenname the value for t_sjjianchu.bumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenname(String bumenname) {
        this.bumenname = bumenname == null ? null : bumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buyuanId
     *
     * @return the value of t_sjjianchu.buyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuyuanid() {
        return buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBuyuanid(Integer buyuanid) {
        this.setBuyuanid(buyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buyuanId
     *
     * @param buyuanid the value for t_sjjianchu.buyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanid(Integer buyuanid) {
        this.buyuanid = buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buyuanName
     *
     * @return the value of t_sjjianchu.buyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuyuanname() {
        return buyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBuyuanname(String buyuanname) {
        this.setBuyuanname(buyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buyuanName
     *
     * @param buyuanname the value for t_sjjianchu.buyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanname(String buyuanname) {
        this.buyuanname = buyuanname == null ? null : buyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yonghuId
     *
     * @return the value of t_sjjianchu.yonghuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuid() {
        return yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withYonghuid(Integer yonghuid) {
        this.setYonghuid(yonghuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yonghuId
     *
     * @param yonghuid the value for t_sjjianchu.yonghuId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuid(Integer yonghuid) {
        this.yonghuid = yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yonghuName
     *
     * @return the value of t_sjjianchu.yonghuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuname() {
        return yonghuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withYonghuname(String yonghuname) {
        this.setYonghuname(yonghuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yonghuName
     *
     * @param yonghuname the value for t_sjjianchu.yonghuName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuname(String yonghuname) {
        this.yonghuname = yonghuname == null ? null : yonghuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byumenId
     *
     * @return the value of t_sjjianchu.byumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByumenid() {
        return byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByumenid(Integer byumenid) {
        this.setByumenid(byumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byumenId
     *
     * @param byumenid the value for t_sjjianchu.byumenId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenid(Integer byumenid) {
        this.byumenid = byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byumenName
     *
     * @return the value of t_sjjianchu.byumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByumenname() {
        return byumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByumenname(String byumenname) {
        this.setByumenname(byumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byumenName
     *
     * @param byumenname the value for t_sjjianchu.byumenName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenname(String byumenname) {
        this.byumenname = byumenname == null ? null : byumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuyuanId
     *
     * @return the value of t_sjjianchu.byuyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuyuanid() {
        return byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByuyuanid(Integer byuyuanid) {
        this.setByuyuanid(byuyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuyuanId
     *
     * @param byuyuanid the value for t_sjjianchu.byuyuanId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanid(Integer byuyuanid) {
        this.byuyuanid = byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuyuanName
     *
     * @return the value of t_sjjianchu.byuyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuyuanname() {
        return byuyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByuyuanname(String byuyuanname) {
        this.setByuyuanname(byuyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuyuanName
     *
     * @param byuyuanname the value for t_sjjianchu.byuyuanName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanname(String byuyuanname) {
        this.byuyuanname = byuyuanname == null ? null : byuyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buzhiId
     *
     * @return the value of t_sjjianchu.buzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuzhiid() {
        return buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBuzhiid(Integer buzhiid) {
        this.setBuzhiid(buzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buzhiId
     *
     * @param buzhiid the value for t_sjjianchu.buzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiid(Integer buzhiid) {
        this.buzhiid = buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buzhiName
     *
     * @return the value of t_sjjianchu.buzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuzhiname() {
        return buzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withBuzhiname(String buzhiname) {
        this.setBuzhiname(buzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buzhiName
     *
     * @param buzhiname the value for t_sjjianchu.buzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiname(String buzhiname) {
        this.buzhiname = buzhiname == null ? null : buzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.roleId
     *
     * @return the value of t_sjjianchu.roleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withRoleid(Integer roleid) {
        this.setRoleid(roleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.roleId
     *
     * @param roleid the value for t_sjjianchu.roleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.roleName
     *
     * @return the value of t_sjjianchu.roleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withRolename(String rolename) {
        this.setRolename(rolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.roleName
     *
     * @param rolename the value for t_sjjianchu.roleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuzhiId
     *
     * @return the value of t_sjjianchu.byuzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuzhiid() {
        return byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByuzhiid(Integer byuzhiid) {
        this.setByuzhiid(byuzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuzhiId
     *
     * @param byuzhiid the value for t_sjjianchu.byuzhiId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiid(Integer byuzhiid) {
        this.byuzhiid = byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuzhiName
     *
     * @return the value of t_sjjianchu.byuzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuzhiname() {
        return byuzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withByuzhiname(String byuzhiname) {
        this.setByuzhiname(byuzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuzhiName
     *
     * @param byuzhiname the value for t_sjjianchu.byuzhiName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiname(String byuzhiname) {
        this.byuzhiname = byuzhiname == null ? null : byuzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yhroleId
     *
     * @return the value of t_sjjianchu.yhroleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYhroleid() {
        return yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withYhroleid(Integer yhroleid) {
        this.setYhroleid(yhroleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yhroleId
     *
     * @param yhroleid the value for t_sjjianchu.yhroleId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhroleid(Integer yhroleid) {
        this.yhroleid = yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yhroleName
     *
     * @return the value of t_sjjianchu.yhroleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYhrolename() {
        return yhrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public JianChuPojo withYhrolename(String yhrolename) {
        this.setYhrolename(yhrolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yhroleName
     *
     * @param yhrolename the value for t_sjjianchu.yhroleName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhrolename(String yhrolename) {
        this.yhrolename = yhrolename == null ? null : yhrolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sjjianchuid=").append(sjjianchuid);
        sb.append(", sjjianchuname=").append(sjjianchuname);
        sb.append(", sjjianchumark=").append(sjjianchumark);
        sb.append(", sjjianchumark1=").append(sjjianchumark1);
        sb.append(", sjjianchumark2=").append(sjjianchumark2);
        sb.append(", sjjianchumark3=").append(sjjianchumark3);
        sb.append(", sjjianchudate=").append(sjjianchudate);
        sb.append(", sjjianchudate1=").append(sjjianchudate1);
        sb.append(", sjjianchuzong=").append(sjjianchuzong);
        sb.append(", sjjianchuzong1=").append(sjjianchuzong1);
        sb.append(", sjjianchuzong2=").append(sjjianchuzong2);
        sb.append(", sjjianchudouble=").append(sjjianchudouble);
        sb.append(", sjjianchudouble1=").append(sjjianchudouble1);
        sb.append(", sjjianchudouble2=").append(sjjianchudouble2);
        sb.append(", sjjianchutype=").append(sjjianchutype);
        sb.append(", sjjianchutype1=").append(sjjianchutype1);
        sb.append(", sjjianchutype2=").append(sjjianchutype2);
        sb.append(", sjqitaid=").append(sjqitaid);
        sb.append(", sjqitaname=").append(sjqitaname);
        sb.append(", sjlaiyuanid=").append(sjlaiyuanid);
        sb.append(", sjlaiyuanname=").append(sjlaiyuanname);
        sb.append(", sjjianchuimg=").append(sjjianchuimg);
        sb.append(", sjjianchuimgname=").append(sjjianchuimgname);
        sb.append(", shujuid=").append(shujuid);
        sb.append(", shujuname=").append(shujuname);
        sb.append(", sjleixingid=").append(sjleixingid);
        sb.append(", sjleixingname=").append(sjleixingname);
        sb.append(", sjxingtaiid=").append(sjxingtaiid);
        sb.append(", sjxingtainame=").append(sjxingtainame);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", bumenid=").append(bumenid);
        sb.append(", bumenname=").append(bumenname);
        sb.append(", buyuanid=").append(buyuanid);
        sb.append(", buyuanname=").append(buyuanname);
        sb.append(", yonghuid=").append(yonghuid);
        sb.append(", yonghuname=").append(yonghuname);
        sb.append(", byumenid=").append(byumenid);
        sb.append(", byumenname=").append(byumenname);
        sb.append(", byuyuanid=").append(byuyuanid);
        sb.append(", byuyuanname=").append(byuyuanname);
        sb.append(", buzhiid=").append(buzhiid);
        sb.append(", buzhiname=").append(buzhiname);
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", byuzhiid=").append(byuzhiid);
        sb.append(", byuzhiname=").append(byuzhiname);
        sb.append(", yhroleid=").append(yhroleid);
        sb.append(", yhrolename=").append(yhrolename);
        sb.append("]");
        return sb.toString();
    }
}