package edu.thn.ciom.pojo;

import java.io.Serializable;
import java.util.Date;

public class LeiXingPojo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingmark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingmark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingPhone
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingdizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjleixingdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date sjleixingdate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingtype1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjleixingdouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double sjleixingdouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingId
     *
     * @return the value of t_sjleixing.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingid() {
        return sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingid(Integer sjleixingid) {
        this.setSjleixingid(sjleixingid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingId
     *
     * @param sjleixingid the value for t_sjleixing.sjleixingId
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingid(Integer sjleixingid) {
        this.sjleixingid = sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingName
     *
     * @return the value of t_sjleixing.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingname() {
        return sjleixingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingname(String sjleixingname) {
        this.setSjleixingname(sjleixingname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingName
     *
     * @param sjleixingname the value for t_sjleixing.sjleixingName
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingname(String sjleixingname) {
        this.sjleixingname = sjleixingname == null ? null : sjleixingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark
     *
     * @return the value of t_sjleixing.sjleixingMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingmark() {
        return sjleixingmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingmark(String sjleixingmark) {
        this.setSjleixingmark(sjleixingmark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark
     *
     * @param sjleixingmark the value for t_sjleixing.sjleixingMark
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingmark(String sjleixingmark) {
        this.sjleixingmark = sjleixingmark == null ? null : sjleixingmark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark1
     *
     * @return the value of t_sjleixing.sjleixingMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingmark1() {
        return sjleixingmark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingmark1(String sjleixingmark1) {
        this.setSjleixingmark1(sjleixingmark1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark1
     *
     * @param sjleixingmark1 the value for t_sjleixing.sjleixingMark1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingmark1(String sjleixingmark1) {
        this.sjleixingmark1 = sjleixingmark1 == null ? null : sjleixingmark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark2
     *
     * @return the value of t_sjleixing.sjleixingMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingmark2() {
        return sjleixingmark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingmark2(String sjleixingmark2) {
        this.setSjleixingmark2(sjleixingmark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark2
     *
     * @param sjleixingmark2 the value for t_sjleixing.sjleixingMark2
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingmark2(String sjleixingmark2) {
        this.sjleixingmark2 = sjleixingmark2 == null ? null : sjleixingmark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingPhone
     *
     * @return the value of t_sjleixing.sjleixingPhone
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingphone() {
        return sjleixingphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingphone(String sjleixingphone) {
        this.setSjleixingphone(sjleixingphone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingPhone
     *
     * @param sjleixingphone the value for t_sjleixing.sjleixingPhone
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingphone(String sjleixingphone) {
        this.sjleixingphone = sjleixingphone == null ? null : sjleixingphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDizhi
     *
     * @return the value of t_sjleixing.sjleixingDizhi
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingdizhi() {
        return sjleixingdizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingdizhi(String sjleixingdizhi) {
        this.setSjleixingdizhi(sjleixingdizhi);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDizhi
     *
     * @param sjleixingdizhi the value for t_sjleixing.sjleixingDizhi
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingdizhi(String sjleixingdizhi) {
        this.sjleixingdizhi = sjleixingdizhi == null ? null : sjleixingdizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDate
     *
     * @return the value of t_sjleixing.sjleixingDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjleixingdate() {
        return sjleixingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingdate(Date sjleixingdate) {
        this.setSjleixingdate(sjleixingdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDate
     *
     * @param sjleixingdate the value for t_sjleixing.sjleixingDate
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingdate(Date sjleixingdate) {
        this.sjleixingdate = sjleixingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDate1
     *
     * @return the value of t_sjleixing.sjleixingDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getSjleixingdate1() {
        return sjleixingdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingdate1(Date sjleixingdate1) {
        this.setSjleixingdate1(sjleixingdate1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDate1
     *
     * @param sjleixingdate1 the value for t_sjleixing.sjleixingDate1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingdate1(Date sjleixingdate1) {
        this.sjleixingdate1 = sjleixingdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingType
     *
     * @return the value of t_sjleixing.sjleixingType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingtype() {
        return sjleixingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingtype(Integer sjleixingtype) {
        this.setSjleixingtype(sjleixingtype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingType
     *
     * @param sjleixingtype the value for t_sjleixing.sjleixingType
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingtype(Integer sjleixingtype) {
        this.sjleixingtype = sjleixingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingType1
     *
     * @return the value of t_sjleixing.sjleixingType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingtype1() {
        return sjleixingtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingtype1(Integer sjleixingtype1) {
        this.setSjleixingtype1(sjleixingtype1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingType1
     *
     * @param sjleixingtype1 the value for t_sjleixing.sjleixingType1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingtype1(Integer sjleixingtype1) {
        this.sjleixingtype1 = sjleixingtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDouble
     *
     * @return the value of t_sjleixing.sjleixingDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjleixingdouble() {
        return sjleixingdouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingdouble(Double sjleixingdouble) {
        this.setSjleixingdouble(sjleixingdouble);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDouble
     *
     * @param sjleixingdouble the value for t_sjleixing.sjleixingDouble
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingdouble(Double sjleixingdouble) {
        this.sjleixingdouble = sjleixingdouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDouble1
     *
     * @return the value of t_sjleixing.sjleixingDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getSjleixingdouble1() {
        return sjleixingdouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public LeiXingPojo withSjleixingdouble1(Double sjleixingdouble1) {
        this.setSjleixingdouble1(sjleixingdouble1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDouble1
     *
     * @param sjleixingdouble1 the value for t_sjleixing.sjleixingDouble1
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingdouble1(Double sjleixingdouble1) {
        this.sjleixingdouble1 = sjleixingdouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sjleixingid=").append(sjleixingid);
        sb.append(", sjleixingname=").append(sjleixingname);
        sb.append(", sjleixingmark=").append(sjleixingmark);
        sb.append(", sjleixingmark1=").append(sjleixingmark1);
        sb.append(", sjleixingmark2=").append(sjleixingmark2);
        sb.append(", sjleixingphone=").append(sjleixingphone);
        sb.append(", sjleixingdizhi=").append(sjleixingdizhi);
        sb.append(", sjleixingdate=").append(sjleixingdate);
        sb.append(", sjleixingdate1=").append(sjleixingdate1);
        sb.append(", sjleixingtype=").append(sjleixingtype);
        sb.append(", sjleixingtype1=").append(sjleixingtype1);
        sb.append(", sjleixingdouble=").append(sjleixingdouble);
        sb.append(", sjleixingdouble1=").append(sjleixingdouble1);
        sb.append("]");
        return sb.toString();
    }
}