package edu.thn.ciom.pojo;

import java.io.Serializable;
import java.util.Date;

public class ShujuPojo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujumark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujumark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujumark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujumark3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date shujudate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date shujudate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuzong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuzong1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujuzong2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double shujudouble;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double shujudouble1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double shujudouble2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDouble3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double shujudouble3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuDouble4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double shujudouble4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujutype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujutype1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer shujutype2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujuimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.shujuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String shujuimgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjleixingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjleixingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.sjxingtaiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer sjxingtaiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.sjxingtaiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String sjxingtainame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer bumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String bumenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buyuanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buyuanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byumenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuyuanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuyuanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buzhiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buzhiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.roleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.roleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuzhiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuzhiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yhroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shuju.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yhrolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuId
     *
     * @return the value of t_shuju.shujuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuid() {
        return shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuid(Integer shujuid) {
        this.setShujuid(shujuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuId
     *
     * @param shujuid the value for t_shuju.shujuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuid(Integer shujuid) {
        this.shujuid = shujuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuName
     *
     * @return the value of t_shuju.shujuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujuname() {
        return shujuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuname(String shujuname) {
        this.setShujuname(shujuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuName
     *
     * @param shujuname the value for t_shuju.shujuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuname(String shujuname) {
        this.shujuname = shujuname == null ? null : shujuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuMark
     *
     * @return the value of t_shuju.shujuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujumark() {
        return shujumark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujumark(String shujumark) {
        this.setShujumark(shujumark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuMark
     *
     * @param shujumark the value for t_shuju.shujuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujumark(String shujumark) {
        this.shujumark = shujumark == null ? null : shujumark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuMark1
     *
     * @return the value of t_shuju.shujuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujumark1() {
        return shujumark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujumark1(String shujumark1) {
        this.setShujumark1(shujumark1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuMark1
     *
     * @param shujumark1 the value for t_shuju.shujuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujumark1(String shujumark1) {
        this.shujumark1 = shujumark1 == null ? null : shujumark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuMark2
     *
     * @return the value of t_shuju.shujuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujumark2() {
        return shujumark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujumark2(String shujumark2) {
        this.setShujumark2(shujumark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuMark2
     *
     * @param shujumark2 the value for t_shuju.shujuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujumark2(String shujumark2) {
        this.shujumark2 = shujumark2 == null ? null : shujumark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuMark3
     *
     * @return the value of t_shuju.shujuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujumark3() {
        return shujumark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujumark3(String shujumark3) {
        this.setShujumark3(shujumark3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuMark3
     *
     * @param shujumark3 the value for t_shuju.shujuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujumark3(String shujumark3) {
        this.shujumark3 = shujumark3 == null ? null : shujumark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDate
     *
     * @return the value of t_shuju.shujuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getShujudate() {
        return shujudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudate(Date shujudate) {
        this.setShujudate(shujudate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDate
     *
     * @param shujudate the value for t_shuju.shujuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudate(Date shujudate) {
        this.shujudate = shujudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDate1
     *
     * @return the value of t_shuju.shujuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getShujudate1() {
        return shujudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudate1(Date shujudate1) {
        this.setShujudate1(shujudate1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDate1
     *
     * @param shujudate1 the value for t_shuju.shujuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudate1(Date shujudate1) {
        this.shujudate1 = shujudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuZong
     *
     * @return the value of t_shuju.shujuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuzong() {
        return shujuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuzong(Integer shujuzong) {
        this.setShujuzong(shujuzong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuZong
     *
     * @param shujuzong the value for t_shuju.shujuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuzong(Integer shujuzong) {
        this.shujuzong = shujuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuZong1
     *
     * @return the value of t_shuju.shujuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuzong1() {
        return shujuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuzong1(Integer shujuzong1) {
        this.setShujuzong1(shujuzong1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuZong1
     *
     * @param shujuzong1 the value for t_shuju.shujuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuzong1(Integer shujuzong1) {
        this.shujuzong1 = shujuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuZong2
     *
     * @return the value of t_shuju.shujuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujuzong2() {
        return shujuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuzong2(Integer shujuzong2) {
        this.setShujuzong2(shujuzong2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuZong2
     *
     * @param shujuzong2 the value for t_shuju.shujuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuzong2(Integer shujuzong2) {
        this.shujuzong2 = shujuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDouble
     *
     * @return the value of t_shuju.shujuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getShujudouble() {
        return shujudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudouble(Double shujudouble) {
        this.setShujudouble(shujudouble);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDouble
     *
     * @param shujudouble the value for t_shuju.shujuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudouble(Double shujudouble) {
        this.shujudouble = shujudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDouble1
     *
     * @return the value of t_shuju.shujuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getShujudouble1() {
        return shujudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudouble1(Double shujudouble1) {
        this.setShujudouble1(shujudouble1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDouble1
     *
     * @param shujudouble1 the value for t_shuju.shujuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudouble1(Double shujudouble1) {
        this.shujudouble1 = shujudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDouble2
     *
     * @return the value of t_shuju.shujuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getShujudouble2() {
        return shujudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudouble2(Double shujudouble2) {
        this.setShujudouble2(shujudouble2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDouble2
     *
     * @param shujudouble2 the value for t_shuju.shujuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudouble2(Double shujudouble2) {
        this.shujudouble2 = shujudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDouble3
     *
     * @return the value of t_shuju.shujuDouble3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getShujudouble3() {
        return shujudouble3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudouble3(Double shujudouble3) {
        this.setShujudouble3(shujudouble3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDouble3
     *
     * @param shujudouble3 the value for t_shuju.shujuDouble3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudouble3(Double shujudouble3) {
        this.shujudouble3 = shujudouble3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuDouble4
     *
     * @return the value of t_shuju.shujuDouble4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getShujudouble4() {
        return shujudouble4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujudouble4(Double shujudouble4) {
        this.setShujudouble4(shujudouble4);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuDouble4
     *
     * @param shujudouble4 the value for t_shuju.shujuDouble4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujudouble4(Double shujudouble4) {
        this.shujudouble4 = shujudouble4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuType
     *
     * @return the value of t_shuju.shujuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujutype() {
        return shujutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujutype(Integer shujutype) {
        this.setShujutype(shujutype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuType
     *
     * @param shujutype the value for t_shuju.shujuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujutype(Integer shujutype) {
        this.shujutype = shujutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuType1
     *
     * @return the value of t_shuju.shujuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujutype1() {
        return shujutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujutype1(Integer shujutype1) {
        this.setShujutype1(shujutype1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuType1
     *
     * @param shujutype1 the value for t_shuju.shujuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujutype1(Integer shujutype1) {
        this.shujutype1 = shujutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuType2
     *
     * @return the value of t_shuju.shujuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getShujutype2() {
        return shujutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujutype2(Integer shujutype2) {
        this.setShujutype2(shujutype2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuType2
     *
     * @param shujutype2 the value for t_shuju.shujuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujutype2(Integer shujutype2) {
        this.shujutype2 = shujutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuImg
     *
     * @return the value of t_shuju.shujuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujuimg() {
        return shujuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuimg(String shujuimg) {
        this.setShujuimg(shujuimg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuImg
     *
     * @param shujuimg the value for t_shuju.shujuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuimg(String shujuimg) {
        this.shujuimg = shujuimg == null ? null : shujuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.shujuImgName
     *
     * @return the value of t_shuju.shujuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getShujuimgname() {
        return shujuimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withShujuimgname(String shujuimgname) {
        this.setShujuimgname(shujuimgname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.shujuImgName
     *
     * @param shujuimgname the value for t_shuju.shujuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setShujuimgname(String shujuimgname) {
        this.shujuimgname = shujuimgname == null ? null : shujuimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.sjleixingId
     *
     * @return the value of t_shuju.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjleixingid() {
        return sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withSjleixingid(Integer sjleixingid) {
        this.setSjleixingid(sjleixingid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.sjleixingId
     *
     * @param sjleixingid the value for t_shuju.sjleixingId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingid(Integer sjleixingid) {
        this.sjleixingid = sjleixingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.sjleixingName
     *
     * @return the value of t_shuju.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjleixingname() {
        return sjleixingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withSjleixingname(String sjleixingname) {
        this.setSjleixingname(sjleixingname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.sjleixingName
     *
     * @param sjleixingname the value for t_shuju.sjleixingName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjleixingname(String sjleixingname) {
        this.sjleixingname = sjleixingname == null ? null : sjleixingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.sjxingtaiId
     *
     * @return the value of t_shuju.sjxingtaiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getSjxingtaiid() {
        return sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withSjxingtaiid(Integer sjxingtaiid) {
        this.setSjxingtaiid(sjxingtaiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.sjxingtaiId
     *
     * @param sjxingtaiid the value for t_shuju.sjxingtaiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtaiid(Integer sjxingtaiid) {
        this.sjxingtaiid = sjxingtaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.sjxingtaiName
     *
     * @return the value of t_shuju.sjxingtaiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getSjxingtainame() {
        return sjxingtainame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withSjxingtainame(String sjxingtainame) {
        this.setSjxingtainame(sjxingtainame);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.sjxingtaiName
     *
     * @param sjxingtainame the value for t_shuju.sjxingtaiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setSjxingtainame(String sjxingtainame) {
        this.sjxingtainame = sjxingtainame == null ? null : sjxingtainame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.userId
     *
     * @return the value of t_shuju.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withUserid(Integer userid) {
        this.setUserid(userid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.userId
     *
     * @param userid the value for t_shuju.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.userName
     *
     * @return the value of t_shuju.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.userName
     *
     * @param username the value for t_shuju.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.bumenId
     *
     * @return the value of t_shuju.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBumenid(Integer bumenid) {
        this.setBumenid(bumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.bumenId
     *
     * @param bumenid the value for t_shuju.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.bumenName
     *
     * @return the value of t_shuju.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBumenname() {
        return bumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBumenname(String bumenname) {
        this.setBumenname(bumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.bumenName
     *
     * @param bumenname the value for t_shuju.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenname(String bumenname) {
        this.bumenname = bumenname == null ? null : bumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.buyuanId
     *
     * @return the value of t_shuju.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuyuanid() {
        return buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBuyuanid(Integer buyuanid) {
        this.setBuyuanid(buyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.buyuanId
     *
     * @param buyuanid the value for t_shuju.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanid(Integer buyuanid) {
        this.buyuanid = buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.buyuanName
     *
     * @return the value of t_shuju.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuyuanname() {
        return buyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBuyuanname(String buyuanname) {
        this.setBuyuanname(buyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.buyuanName
     *
     * @param buyuanname the value for t_shuju.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanname(String buyuanname) {
        this.buyuanname = buyuanname == null ? null : buyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.yonghuId
     *
     * @return the value of t_shuju.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuid() {
        return yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withYonghuid(Integer yonghuid) {
        this.setYonghuid(yonghuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.yonghuId
     *
     * @param yonghuid the value for t_shuju.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuid(Integer yonghuid) {
        this.yonghuid = yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.yonghuName
     *
     * @return the value of t_shuju.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuname() {
        return yonghuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withYonghuname(String yonghuname) {
        this.setYonghuname(yonghuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.yonghuName
     *
     * @param yonghuname the value for t_shuju.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuname(String yonghuname) {
        this.yonghuname = yonghuname == null ? null : yonghuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byumenId
     *
     * @return the value of t_shuju.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByumenid() {
        return byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByumenid(Integer byumenid) {
        this.setByumenid(byumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byumenId
     *
     * @param byumenid the value for t_shuju.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenid(Integer byumenid) {
        this.byumenid = byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byumenName
     *
     * @return the value of t_shuju.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByumenname() {
        return byumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByumenname(String byumenname) {
        this.setByumenname(byumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byumenName
     *
     * @param byumenname the value for t_shuju.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenname(String byumenname) {
        this.byumenname = byumenname == null ? null : byumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byuyuanId
     *
     * @return the value of t_shuju.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuyuanid() {
        return byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByuyuanid(Integer byuyuanid) {
        this.setByuyuanid(byuyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byuyuanId
     *
     * @param byuyuanid the value for t_shuju.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanid(Integer byuyuanid) {
        this.byuyuanid = byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byuyuanName
     *
     * @return the value of t_shuju.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuyuanname() {
        return byuyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByuyuanname(String byuyuanname) {
        this.setByuyuanname(byuyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byuyuanName
     *
     * @param byuyuanname the value for t_shuju.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanname(String byuyuanname) {
        this.byuyuanname = byuyuanname == null ? null : byuyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.buzhiId
     *
     * @return the value of t_shuju.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuzhiid() {
        return buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBuzhiid(Integer buzhiid) {
        this.setBuzhiid(buzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.buzhiId
     *
     * @param buzhiid the value for t_shuju.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiid(Integer buzhiid) {
        this.buzhiid = buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.buzhiName
     *
     * @return the value of t_shuju.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuzhiname() {
        return buzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withBuzhiname(String buzhiname) {
        this.setBuzhiname(buzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.buzhiName
     *
     * @param buzhiname the value for t_shuju.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiname(String buzhiname) {
        this.buzhiname = buzhiname == null ? null : buzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.roleId
     *
     * @return the value of t_shuju.roleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withRoleid(Integer roleid) {
        this.setRoleid(roleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.roleId
     *
     * @param roleid the value for t_shuju.roleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.roleName
     *
     * @return the value of t_shuju.roleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withRolename(String rolename) {
        this.setRolename(rolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.roleName
     *
     * @param rolename the value for t_shuju.roleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byuzhiId
     *
     * @return the value of t_shuju.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuzhiid() {
        return byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByuzhiid(Integer byuzhiid) {
        this.setByuzhiid(byuzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byuzhiId
     *
     * @param byuzhiid the value for t_shuju.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiid(Integer byuzhiid) {
        this.byuzhiid = byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.byuzhiName
     *
     * @return the value of t_shuju.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuzhiname() {
        return byuzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withByuzhiname(String byuzhiname) {
        this.setByuzhiname(byuzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.byuzhiName
     *
     * @param byuzhiname the value for t_shuju.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiname(String byuzhiname) {
        this.byuzhiname = byuzhiname == null ? null : byuzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.yhroleId
     *
     * @return the value of t_shuju.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYhroleid() {
        return yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withYhroleid(Integer yhroleid) {
        this.setYhroleid(yhroleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.yhroleId
     *
     * @param yhroleid the value for t_shuju.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhroleid(Integer yhroleid) {
        this.yhroleid = yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shuju.yhroleName
     *
     * @return the value of t_shuju.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYhrolename() {
        return yhrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public ShujuPojo withYhrolename(String yhrolename) {
        this.setYhrolename(yhrolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shuju.yhroleName
     *
     * @param yhrolename the value for t_shuju.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhrolename(String yhrolename) {
        this.yhrolename = yhrolename == null ? null : yhrolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shujuid=").append(shujuid);
        sb.append(", shujuname=").append(shujuname);
        sb.append(", shujumark=").append(shujumark);
        sb.append(", shujumark1=").append(shujumark1);
        sb.append(", shujumark2=").append(shujumark2);
        sb.append(", shujumark3=").append(shujumark3);
        sb.append(", shujudate=").append(shujudate);
        sb.append(", shujudate1=").append(shujudate1);
        sb.append(", shujuzong=").append(shujuzong);
        sb.append(", shujuzong1=").append(shujuzong1);
        sb.append(", shujuzong2=").append(shujuzong2);
        sb.append(", shujudouble=").append(shujudouble);
        sb.append(", shujudouble1=").append(shujudouble1);
        sb.append(", shujudouble2=").append(shujudouble2);
        sb.append(", shujudouble3=").append(shujudouble3);
        sb.append(", shujudouble4=").append(shujudouble4);
        sb.append(", shujutype=").append(shujutype);
        sb.append(", shujutype1=").append(shujutype1);
        sb.append(", shujutype2=").append(shujutype2);
        sb.append(", shujuimg=").append(shujuimg);
        sb.append(", shujuimgname=").append(shujuimgname);
        sb.append(", sjleixingid=").append(sjleixingid);
        sb.append(", sjleixingname=").append(sjleixingname);
        sb.append(", sjxingtaiid=").append(sjxingtaiid);
        sb.append(", sjxingtainame=").append(sjxingtainame);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", bumenid=").append(bumenid);
        sb.append(", bumenname=").append(bumenname);
        sb.append(", buyuanid=").append(buyuanid);
        sb.append(", buyuanname=").append(buyuanname);
        sb.append(", yonghuid=").append(yonghuid);
        sb.append(", yonghuname=").append(yonghuname);
        sb.append(", byumenid=").append(byumenid);
        sb.append(", byumenname=").append(byumenname);
        sb.append(", byuyuanid=").append(byuyuanid);
        sb.append(", byuyuanname=").append(byuyuanname);
        sb.append(", buzhiid=").append(buzhiid);
        sb.append(", buzhiname=").append(buzhiname);
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", byuzhiid=").append(byuzhiid);
        sb.append(", byuzhiname=").append(byuzhiname);
        sb.append(", yhroleid=").append(yhroleid);
        sb.append(", yhrolename=").append(yhrolename);
        sb.append("]");
        return sb.toString();
    }
}