package edu.thn.ciom.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserPojoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public UserPojoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIsNull() {
            addCriterion("userPassword is null");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIsNotNull() {
            addCriterion("userPassword is not null");
            return (Criteria) this;
        }

        public Criteria andUserpasswordEqualTo(String value) {
            addCriterion("userPassword =", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotEqualTo(String value) {
            addCriterion("userPassword <>", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordGreaterThan(String value) {
            addCriterion("userPassword >", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("userPassword >=", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLessThan(String value) {
            addCriterion("userPassword <", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLessThanOrEqualTo(String value) {
            addCriterion("userPassword <=", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLike(String value) {
            addCriterion("userPassword like", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotLike(String value) {
            addCriterion("userPassword not like", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIn(List<String> values) {
            addCriterion("userPassword in", values, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotIn(List<String> values) {
            addCriterion("userPassword not in", values, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordBetween(String value1, String value2) {
            addCriterion("userPassword between", value1, value2, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotBetween(String value1, String value2) {
            addCriterion("userPassword not between", value1, value2, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserxingmingIsNull() {
            addCriterion("userXingming is null");
            return (Criteria) this;
        }

        public Criteria andUserxingmingIsNotNull() {
            addCriterion("userXingming is not null");
            return (Criteria) this;
        }

        public Criteria andUserxingmingEqualTo(String value) {
            addCriterion("userXingming =", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingNotEqualTo(String value) {
            addCriterion("userXingming <>", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingGreaterThan(String value) {
            addCriterion("userXingming >", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingGreaterThanOrEqualTo(String value) {
            addCriterion("userXingming >=", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingLessThan(String value) {
            addCriterion("userXingming <", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingLessThanOrEqualTo(String value) {
            addCriterion("userXingming <=", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingLike(String value) {
            addCriterion("userXingming like", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingNotLike(String value) {
            addCriterion("userXingming not like", value, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingIn(List<String> values) {
            addCriterion("userXingming in", values, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingNotIn(List<String> values) {
            addCriterion("userXingming not in", values, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingBetween(String value1, String value2) {
            addCriterion("userXingming between", value1, value2, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUserxingmingNotBetween(String value1, String value2) {
            addCriterion("userXingming not between", value1, value2, "userxingming");
            return (Criteria) this;
        }

        public Criteria andUsersexIsNull() {
            addCriterion("userSex is null");
            return (Criteria) this;
        }

        public Criteria andUsersexIsNotNull() {
            addCriterion("userSex is not null");
            return (Criteria) this;
        }

        public Criteria andUsersexEqualTo(Integer value) {
            addCriterion("userSex =", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexNotEqualTo(Integer value) {
            addCriterion("userSex <>", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexGreaterThan(Integer value) {
            addCriterion("userSex >", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexGreaterThanOrEqualTo(Integer value) {
            addCriterion("userSex >=", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexLessThan(Integer value) {
            addCriterion("userSex <", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexLessThanOrEqualTo(Integer value) {
            addCriterion("userSex <=", value, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexIn(List<Integer> values) {
            addCriterion("userSex in", values, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexNotIn(List<Integer> values) {
            addCriterion("userSex not in", values, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexBetween(Integer value1, Integer value2) {
            addCriterion("userSex between", value1, value2, "usersex");
            return (Criteria) this;
        }

        public Criteria andUsersexNotBetween(Integer value1, Integer value2) {
            addCriterion("userSex not between", value1, value2, "usersex");
            return (Criteria) this;
        }

        public Criteria andUserageIsNull() {
            addCriterion("userAge is null");
            return (Criteria) this;
        }

        public Criteria andUserageIsNotNull() {
            addCriterion("userAge is not null");
            return (Criteria) this;
        }

        public Criteria andUserageEqualTo(Integer value) {
            addCriterion("userAge =", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageNotEqualTo(Integer value) {
            addCriterion("userAge <>", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageGreaterThan(Integer value) {
            addCriterion("userAge >", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageGreaterThanOrEqualTo(Integer value) {
            addCriterion("userAge >=", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageLessThan(Integer value) {
            addCriterion("userAge <", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageLessThanOrEqualTo(Integer value) {
            addCriterion("userAge <=", value, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageIn(List<Integer> values) {
            addCriterion("userAge in", values, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageNotIn(List<Integer> values) {
            addCriterion("userAge not in", values, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageBetween(Integer value1, Integer value2) {
            addCriterion("userAge between", value1, value2, "userage");
            return (Criteria) this;
        }

        public Criteria andUserageNotBetween(Integer value1, Integer value2) {
            addCriterion("userAge not between", value1, value2, "userage");
            return (Criteria) this;
        }

        public Criteria andUserminzuIsNull() {
            addCriterion("userMinzu is null");
            return (Criteria) this;
        }

        public Criteria andUserminzuIsNotNull() {
            addCriterion("userMinzu is not null");
            return (Criteria) this;
        }

        public Criteria andUserminzuEqualTo(String value) {
            addCriterion("userMinzu =", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuNotEqualTo(String value) {
            addCriterion("userMinzu <>", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuGreaterThan(String value) {
            addCriterion("userMinzu >", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuGreaterThanOrEqualTo(String value) {
            addCriterion("userMinzu >=", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuLessThan(String value) {
            addCriterion("userMinzu <", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuLessThanOrEqualTo(String value) {
            addCriterion("userMinzu <=", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuLike(String value) {
            addCriterion("userMinzu like", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuNotLike(String value) {
            addCriterion("userMinzu not like", value, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuIn(List<String> values) {
            addCriterion("userMinzu in", values, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuNotIn(List<String> values) {
            addCriterion("userMinzu not in", values, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuBetween(String value1, String value2) {
            addCriterion("userMinzu between", value1, value2, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserminzuNotBetween(String value1, String value2) {
            addCriterion("userMinzu not between", value1, value2, "userminzu");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNull() {
            addCriterion("userPhone is null");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNotNull() {
            addCriterion("userPhone is not null");
            return (Criteria) this;
        }

        public Criteria andUserphoneEqualTo(String value) {
            addCriterion("userPhone =", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotEqualTo(String value) {
            addCriterion("userPhone <>", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThan(String value) {
            addCriterion("userPhone >", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThanOrEqualTo(String value) {
            addCriterion("userPhone >=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThan(String value) {
            addCriterion("userPhone <", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThanOrEqualTo(String value) {
            addCriterion("userPhone <=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLike(String value) {
            addCriterion("userPhone like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotLike(String value) {
            addCriterion("userPhone not like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneIn(List<String> values) {
            addCriterion("userPhone in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotIn(List<String> values) {
            addCriterion("userPhone not in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneBetween(String value1, String value2) {
            addCriterion("userPhone between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotBetween(String value1, String value2) {
            addCriterion("userPhone not between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUsermarkIsNull() {
            addCriterion("userMark is null");
            return (Criteria) this;
        }

        public Criteria andUsermarkIsNotNull() {
            addCriterion("userMark is not null");
            return (Criteria) this;
        }

        public Criteria andUsermarkEqualTo(String value) {
            addCriterion("userMark =", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotEqualTo(String value) {
            addCriterion("userMark <>", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkGreaterThan(String value) {
            addCriterion("userMark >", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkGreaterThanOrEqualTo(String value) {
            addCriterion("userMark >=", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLessThan(String value) {
            addCriterion("userMark <", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLessThanOrEqualTo(String value) {
            addCriterion("userMark <=", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLike(String value) {
            addCriterion("userMark like", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotLike(String value) {
            addCriterion("userMark not like", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkIn(List<String> values) {
            addCriterion("userMark in", values, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotIn(List<String> values) {
            addCriterion("userMark not in", values, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkBetween(String value1, String value2) {
            addCriterion("userMark between", value1, value2, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotBetween(String value1, String value2) {
            addCriterion("userMark not between", value1, value2, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermark1IsNull() {
            addCriterion("userMark1 is null");
            return (Criteria) this;
        }

        public Criteria andUsermark1IsNotNull() {
            addCriterion("userMark1 is not null");
            return (Criteria) this;
        }

        public Criteria andUsermark1EqualTo(String value) {
            addCriterion("userMark1 =", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1NotEqualTo(String value) {
            addCriterion("userMark1 <>", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1GreaterThan(String value) {
            addCriterion("userMark1 >", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1GreaterThanOrEqualTo(String value) {
            addCriterion("userMark1 >=", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1LessThan(String value) {
            addCriterion("userMark1 <", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1LessThanOrEqualTo(String value) {
            addCriterion("userMark1 <=", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1Like(String value) {
            addCriterion("userMark1 like", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1NotLike(String value) {
            addCriterion("userMark1 not like", value, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1In(List<String> values) {
            addCriterion("userMark1 in", values, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1NotIn(List<String> values) {
            addCriterion("userMark1 not in", values, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1Between(String value1, String value2) {
            addCriterion("userMark1 between", value1, value2, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark1NotBetween(String value1, String value2) {
            addCriterion("userMark1 not between", value1, value2, "usermark1");
            return (Criteria) this;
        }

        public Criteria andUsermark2IsNull() {
            addCriterion("userMark2 is null");
            return (Criteria) this;
        }

        public Criteria andUsermark2IsNotNull() {
            addCriterion("userMark2 is not null");
            return (Criteria) this;
        }

        public Criteria andUsermark2EqualTo(String value) {
            addCriterion("userMark2 =", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2NotEqualTo(String value) {
            addCriterion("userMark2 <>", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2GreaterThan(String value) {
            addCriterion("userMark2 >", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2GreaterThanOrEqualTo(String value) {
            addCriterion("userMark2 >=", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2LessThan(String value) {
            addCriterion("userMark2 <", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2LessThanOrEqualTo(String value) {
            addCriterion("userMark2 <=", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2Like(String value) {
            addCriterion("userMark2 like", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2NotLike(String value) {
            addCriterion("userMark2 not like", value, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2In(List<String> values) {
            addCriterion("userMark2 in", values, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2NotIn(List<String> values) {
            addCriterion("userMark2 not in", values, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2Between(String value1, String value2) {
            addCriterion("userMark2 between", value1, value2, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark2NotBetween(String value1, String value2) {
            addCriterion("userMark2 not between", value1, value2, "usermark2");
            return (Criteria) this;
        }

        public Criteria andUsermark3IsNull() {
            addCriterion("userMark3 is null");
            return (Criteria) this;
        }

        public Criteria andUsermark3IsNotNull() {
            addCriterion("userMark3 is not null");
            return (Criteria) this;
        }

        public Criteria andUsermark3EqualTo(String value) {
            addCriterion("userMark3 =", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3NotEqualTo(String value) {
            addCriterion("userMark3 <>", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3GreaterThan(String value) {
            addCriterion("userMark3 >", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3GreaterThanOrEqualTo(String value) {
            addCriterion("userMark3 >=", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3LessThan(String value) {
            addCriterion("userMark3 <", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3LessThanOrEqualTo(String value) {
            addCriterion("userMark3 <=", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3Like(String value) {
            addCriterion("userMark3 like", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3NotLike(String value) {
            addCriterion("userMark3 not like", value, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3In(List<String> values) {
            addCriterion("userMark3 in", values, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3NotIn(List<String> values) {
            addCriterion("userMark3 not in", values, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3Between(String value1, String value2) {
            addCriterion("userMark3 between", value1, value2, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark3NotBetween(String value1, String value2) {
            addCriterion("userMark3 not between", value1, value2, "usermark3");
            return (Criteria) this;
        }

        public Criteria andUsermark4IsNull() {
            addCriterion("userMark4 is null");
            return (Criteria) this;
        }

        public Criteria andUsermark4IsNotNull() {
            addCriterion("userMark4 is not null");
            return (Criteria) this;
        }

        public Criteria andUsermark4EqualTo(String value) {
            addCriterion("userMark4 =", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4NotEqualTo(String value) {
            addCriterion("userMark4 <>", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4GreaterThan(String value) {
            addCriterion("userMark4 >", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4GreaterThanOrEqualTo(String value) {
            addCriterion("userMark4 >=", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4LessThan(String value) {
            addCriterion("userMark4 <", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4LessThanOrEqualTo(String value) {
            addCriterion("userMark4 <=", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4Like(String value) {
            addCriterion("userMark4 like", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4NotLike(String value) {
            addCriterion("userMark4 not like", value, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4In(List<String> values) {
            addCriterion("userMark4 in", values, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4NotIn(List<String> values) {
            addCriterion("userMark4 not in", values, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4Between(String value1, String value2) {
            addCriterion("userMark4 between", value1, value2, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUsermark4NotBetween(String value1, String value2) {
            addCriterion("userMark4 not between", value1, value2, "usermark4");
            return (Criteria) this;
        }

        public Criteria andUserdateIsNull() {
            addCriterion("userDate is null");
            return (Criteria) this;
        }

        public Criteria andUserdateIsNotNull() {
            addCriterion("userDate is not null");
            return (Criteria) this;
        }

        public Criteria andUserdateEqualTo(Date value) {
            addCriterionForJDBCDate("userDate =", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("userDate <>", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateGreaterThan(Date value) {
            addCriterionForJDBCDate("userDate >", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate >=", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateLessThan(Date value) {
            addCriterionForJDBCDate("userDate <", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate <=", value, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateIn(List<Date> values) {
            addCriterionForJDBCDate("userDate in", values, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("userDate not in", values, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate between", value1, value2, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate not between", value1, value2, "userdate");
            return (Criteria) this;
        }

        public Criteria andUserdate1IsNull() {
            addCriterion("userDate1 is null");
            return (Criteria) this;
        }

        public Criteria andUserdate1IsNotNull() {
            addCriterion("userDate1 is not null");
            return (Criteria) this;
        }

        public Criteria andUserdate1EqualTo(Date value) {
            addCriterionForJDBCDate("userDate1 =", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1NotEqualTo(Date value) {
            addCriterionForJDBCDate("userDate1 <>", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1GreaterThan(Date value) {
            addCriterionForJDBCDate("userDate1 >", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate1 >=", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1LessThan(Date value) {
            addCriterionForJDBCDate("userDate1 <", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate1 <=", value, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1In(List<Date> values) {
            addCriterionForJDBCDate("userDate1 in", values, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1NotIn(List<Date> values) {
            addCriterionForJDBCDate("userDate1 not in", values, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1Between(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate1 between", value1, value2, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate1NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate1 not between", value1, value2, "userdate1");
            return (Criteria) this;
        }

        public Criteria andUserdate2IsNull() {
            addCriterion("userDate2 is null");
            return (Criteria) this;
        }

        public Criteria andUserdate2IsNotNull() {
            addCriterion("userDate2 is not null");
            return (Criteria) this;
        }

        public Criteria andUserdate2EqualTo(Date value) {
            addCriterionForJDBCDate("userDate2 =", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2NotEqualTo(Date value) {
            addCriterionForJDBCDate("userDate2 <>", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2GreaterThan(Date value) {
            addCriterionForJDBCDate("userDate2 >", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate2 >=", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2LessThan(Date value) {
            addCriterionForJDBCDate("userDate2 <", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("userDate2 <=", value, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2In(List<Date> values) {
            addCriterionForJDBCDate("userDate2 in", values, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2NotIn(List<Date> values) {
            addCriterionForJDBCDate("userDate2 not in", values, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2Between(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate2 between", value1, value2, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUserdate2NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("userDate2 not between", value1, value2, "userdate2");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("userType is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("userType is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(Integer value) {
            addCriterion("userType =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(Integer value) {
            addCriterion("userType <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(Integer value) {
            addCriterion("userType >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("userType >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(Integer value) {
            addCriterion("userType <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(Integer value) {
            addCriterion("userType <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<Integer> values) {
            addCriterion("userType in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<Integer> values) {
            addCriterion("userType not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(Integer value1, Integer value2) {
            addCriterion("userType between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("userType not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertype1IsNull() {
            addCriterion("userType1 is null");
            return (Criteria) this;
        }

        public Criteria andUsertype1IsNotNull() {
            addCriterion("userType1 is not null");
            return (Criteria) this;
        }

        public Criteria andUsertype1EqualTo(Integer value) {
            addCriterion("userType1 =", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1NotEqualTo(Integer value) {
            addCriterion("userType1 <>", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1GreaterThan(Integer value) {
            addCriterion("userType1 >", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1GreaterThanOrEqualTo(Integer value) {
            addCriterion("userType1 >=", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1LessThan(Integer value) {
            addCriterion("userType1 <", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1LessThanOrEqualTo(Integer value) {
            addCriterion("userType1 <=", value, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1In(List<Integer> values) {
            addCriterion("userType1 in", values, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1NotIn(List<Integer> values) {
            addCriterion("userType1 not in", values, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1Between(Integer value1, Integer value2) {
            addCriterion("userType1 between", value1, value2, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype1NotBetween(Integer value1, Integer value2) {
            addCriterion("userType1 not between", value1, value2, "usertype1");
            return (Criteria) this;
        }

        public Criteria andUsertype2IsNull() {
            addCriterion("userType2 is null");
            return (Criteria) this;
        }

        public Criteria andUsertype2IsNotNull() {
            addCriterion("userType2 is not null");
            return (Criteria) this;
        }

        public Criteria andUsertype2EqualTo(Integer value) {
            addCriterion("userType2 =", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2NotEqualTo(Integer value) {
            addCriterion("userType2 <>", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2GreaterThan(Integer value) {
            addCriterion("userType2 >", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2GreaterThanOrEqualTo(Integer value) {
            addCriterion("userType2 >=", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2LessThan(Integer value) {
            addCriterion("userType2 <", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2LessThanOrEqualTo(Integer value) {
            addCriterion("userType2 <=", value, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2In(List<Integer> values) {
            addCriterion("userType2 in", values, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2NotIn(List<Integer> values) {
            addCriterion("userType2 not in", values, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2Between(Integer value1, Integer value2) {
            addCriterion("userType2 between", value1, value2, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUsertype2NotBetween(Integer value1, Integer value2) {
            addCriterion("userType2 not between", value1, value2, "usertype2");
            return (Criteria) this;
        }

        public Criteria andUserdoubleIsNull() {
            addCriterion("userDouble is null");
            return (Criteria) this;
        }

        public Criteria andUserdoubleIsNotNull() {
            addCriterion("userDouble is not null");
            return (Criteria) this;
        }

        public Criteria andUserdoubleEqualTo(Double value) {
            addCriterion("userDouble =", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleNotEqualTo(Double value) {
            addCriterion("userDouble <>", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleGreaterThan(Double value) {
            addCriterion("userDouble >", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleGreaterThanOrEqualTo(Double value) {
            addCriterion("userDouble >=", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleLessThan(Double value) {
            addCriterion("userDouble <", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleLessThanOrEqualTo(Double value) {
            addCriterion("userDouble <=", value, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleIn(List<Double> values) {
            addCriterion("userDouble in", values, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleNotIn(List<Double> values) {
            addCriterion("userDouble not in", values, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleBetween(Double value1, Double value2) {
            addCriterion("userDouble between", value1, value2, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdoubleNotBetween(Double value1, Double value2) {
            addCriterion("userDouble not between", value1, value2, "userdouble");
            return (Criteria) this;
        }

        public Criteria andUserdouble1IsNull() {
            addCriterion("userDouble1 is null");
            return (Criteria) this;
        }

        public Criteria andUserdouble1IsNotNull() {
            addCriterion("userDouble1 is not null");
            return (Criteria) this;
        }

        public Criteria andUserdouble1EqualTo(Double value) {
            addCriterion("userDouble1 =", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1NotEqualTo(Double value) {
            addCriterion("userDouble1 <>", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1GreaterThan(Double value) {
            addCriterion("userDouble1 >", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1GreaterThanOrEqualTo(Double value) {
            addCriterion("userDouble1 >=", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1LessThan(Double value) {
            addCriterion("userDouble1 <", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1LessThanOrEqualTo(Double value) {
            addCriterion("userDouble1 <=", value, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1In(List<Double> values) {
            addCriterion("userDouble1 in", values, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1NotIn(List<Double> values) {
            addCriterion("userDouble1 not in", values, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1Between(Double value1, Double value2) {
            addCriterion("userDouble1 between", value1, value2, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble1NotBetween(Double value1, Double value2) {
            addCriterion("userDouble1 not between", value1, value2, "userdouble1");
            return (Criteria) this;
        }

        public Criteria andUserdouble2IsNull() {
            addCriterion("userDouble2 is null");
            return (Criteria) this;
        }

        public Criteria andUserdouble2IsNotNull() {
            addCriterion("userDouble2 is not null");
            return (Criteria) this;
        }

        public Criteria andUserdouble2EqualTo(Double value) {
            addCriterion("userDouble2 =", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2NotEqualTo(Double value) {
            addCriterion("userDouble2 <>", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2GreaterThan(Double value) {
            addCriterion("userDouble2 >", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2GreaterThanOrEqualTo(Double value) {
            addCriterion("userDouble2 >=", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2LessThan(Double value) {
            addCriterion("userDouble2 <", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2LessThanOrEqualTo(Double value) {
            addCriterion("userDouble2 <=", value, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2In(List<Double> values) {
            addCriterion("userDouble2 in", values, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2NotIn(List<Double> values) {
            addCriterion("userDouble2 not in", values, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2Between(Double value1, Double value2) {
            addCriterion("userDouble2 between", value1, value2, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserdouble2NotBetween(Double value1, Double value2) {
            addCriterion("userDouble2 not between", value1, value2, "userdouble2");
            return (Criteria) this;
        }

        public Criteria andUserzongIsNull() {
            addCriterion("userZong is null");
            return (Criteria) this;
        }

        public Criteria andUserzongIsNotNull() {
            addCriterion("userZong is not null");
            return (Criteria) this;
        }

        public Criteria andUserzongEqualTo(Integer value) {
            addCriterion("userZong =", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongNotEqualTo(Integer value) {
            addCriterion("userZong <>", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongGreaterThan(Integer value) {
            addCriterion("userZong >", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongGreaterThanOrEqualTo(Integer value) {
            addCriterion("userZong >=", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongLessThan(Integer value) {
            addCriterion("userZong <", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongLessThanOrEqualTo(Integer value) {
            addCriterion("userZong <=", value, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongIn(List<Integer> values) {
            addCriterion("userZong in", values, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongNotIn(List<Integer> values) {
            addCriterion("userZong not in", values, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongBetween(Integer value1, Integer value2) {
            addCriterion("userZong between", value1, value2, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzongNotBetween(Integer value1, Integer value2) {
            addCriterion("userZong not between", value1, value2, "userzong");
            return (Criteria) this;
        }

        public Criteria andUserzong1IsNull() {
            addCriterion("userZong1 is null");
            return (Criteria) this;
        }

        public Criteria andUserzong1IsNotNull() {
            addCriterion("userZong1 is not null");
            return (Criteria) this;
        }

        public Criteria andUserzong1EqualTo(Integer value) {
            addCriterion("userZong1 =", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1NotEqualTo(Integer value) {
            addCriterion("userZong1 <>", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1GreaterThan(Integer value) {
            addCriterion("userZong1 >", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1GreaterThanOrEqualTo(Integer value) {
            addCriterion("userZong1 >=", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1LessThan(Integer value) {
            addCriterion("userZong1 <", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1LessThanOrEqualTo(Integer value) {
            addCriterion("userZong1 <=", value, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1In(List<Integer> values) {
            addCriterion("userZong1 in", values, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1NotIn(List<Integer> values) {
            addCriterion("userZong1 not in", values, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1Between(Integer value1, Integer value2) {
            addCriterion("userZong1 between", value1, value2, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong1NotBetween(Integer value1, Integer value2) {
            addCriterion("userZong1 not between", value1, value2, "userzong1");
            return (Criteria) this;
        }

        public Criteria andUserzong2IsNull() {
            addCriterion("userZong2 is null");
            return (Criteria) this;
        }

        public Criteria andUserzong2IsNotNull() {
            addCriterion("userZong2 is not null");
            return (Criteria) this;
        }

        public Criteria andUserzong2EqualTo(Integer value) {
            addCriterion("userZong2 =", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2NotEqualTo(Integer value) {
            addCriterion("userZong2 <>", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2GreaterThan(Integer value) {
            addCriterion("userZong2 >", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2GreaterThanOrEqualTo(Integer value) {
            addCriterion("userZong2 >=", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2LessThan(Integer value) {
            addCriterion("userZong2 <", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2LessThanOrEqualTo(Integer value) {
            addCriterion("userZong2 <=", value, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2In(List<Integer> values) {
            addCriterion("userZong2 in", values, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2NotIn(List<Integer> values) {
            addCriterion("userZong2 not in", values, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2Between(Integer value1, Integer value2) {
            addCriterion("userZong2 between", value1, value2, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserzong2NotBetween(Integer value1, Integer value2) {
            addCriterion("userZong2 not between", value1, value2, "userzong2");
            return (Criteria) this;
        }

        public Criteria andUserimgIsNull() {
            addCriterion("userImg is null");
            return (Criteria) this;
        }

        public Criteria andUserimgIsNotNull() {
            addCriterion("userImg is not null");
            return (Criteria) this;
        }

        public Criteria andUserimgEqualTo(String value) {
            addCriterion("userImg =", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgNotEqualTo(String value) {
            addCriterion("userImg <>", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgGreaterThan(String value) {
            addCriterion("userImg >", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgGreaterThanOrEqualTo(String value) {
            addCriterion("userImg >=", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgLessThan(String value) {
            addCriterion("userImg <", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgLessThanOrEqualTo(String value) {
            addCriterion("userImg <=", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgLike(String value) {
            addCriterion("userImg like", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgNotLike(String value) {
            addCriterion("userImg not like", value, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgIn(List<String> values) {
            addCriterion("userImg in", values, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgNotIn(List<String> values) {
            addCriterion("userImg not in", values, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgBetween(String value1, String value2) {
            addCriterion("userImg between", value1, value2, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgNotBetween(String value1, String value2) {
            addCriterion("userImg not between", value1, value2, "userimg");
            return (Criteria) this;
        }

        public Criteria andUserimgnameIsNull() {
            addCriterion("userImgName is null");
            return (Criteria) this;
        }

        public Criteria andUserimgnameIsNotNull() {
            addCriterion("userImgName is not null");
            return (Criteria) this;
        }

        public Criteria andUserimgnameEqualTo(String value) {
            addCriterion("userImgName =", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameNotEqualTo(String value) {
            addCriterion("userImgName <>", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameGreaterThan(String value) {
            addCriterion("userImgName >", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameGreaterThanOrEqualTo(String value) {
            addCriterion("userImgName >=", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameLessThan(String value) {
            addCriterion("userImgName <", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameLessThanOrEqualTo(String value) {
            addCriterion("userImgName <=", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameLike(String value) {
            addCriterion("userImgName like", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameNotLike(String value) {
            addCriterion("userImgName not like", value, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameIn(List<String> values) {
            addCriterion("userImgName in", values, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameNotIn(List<String> values) {
            addCriterion("userImgName not in", values, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameBetween(String value1, String value2) {
            addCriterion("userImgName between", value1, value2, "userimgname");
            return (Criteria) this;
        }

        public Criteria andUserimgnameNotBetween(String value1, String value2) {
            addCriterion("userImgName not between", value1, value2, "userimgname");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("roleId is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("roleId is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(Integer value) {
            addCriterion("roleId =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(Integer value) {
            addCriterion("roleId <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(Integer value) {
            addCriterion("roleId >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("roleId >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(Integer value) {
            addCriterion("roleId <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(Integer value) {
            addCriterion("roleId <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<Integer> values) {
            addCriterion("roleId in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<Integer> values) {
            addCriterion("roleId not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(Integer value1, Integer value2) {
            addCriterion("roleId between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(Integer value1, Integer value2) {
            addCriterion("roleId not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNull() {
            addCriterion("roleName is null");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNotNull() {
            addCriterion("roleName is not null");
            return (Criteria) this;
        }

        public Criteria andRolenameEqualTo(String value) {
            addCriterion("roleName =", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotEqualTo(String value) {
            addCriterion("roleName <>", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThan(String value) {
            addCriterion("roleName >", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThanOrEqualTo(String value) {
            addCriterion("roleName >=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThan(String value) {
            addCriterion("roleName <", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThanOrEqualTo(String value) {
            addCriterion("roleName <=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLike(String value) {
            addCriterion("roleName like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotLike(String value) {
            addCriterion("roleName not like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameIn(List<String> values) {
            addCriterion("roleName in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotIn(List<String> values) {
            addCriterion("roleName not in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameBetween(String value1, String value2) {
            addCriterion("roleName between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotBetween(String value1, String value2) {
            addCriterion("roleName not between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andBumenidIsNull() {
            addCriterion("bumenId is null");
            return (Criteria) this;
        }

        public Criteria andBumenidIsNotNull() {
            addCriterion("bumenId is not null");
            return (Criteria) this;
        }

        public Criteria andBumenidEqualTo(Integer value) {
            addCriterion("bumenId =", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidNotEqualTo(Integer value) {
            addCriterion("bumenId <>", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidGreaterThan(Integer value) {
            addCriterion("bumenId >", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bumenId >=", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidLessThan(Integer value) {
            addCriterion("bumenId <", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidLessThanOrEqualTo(Integer value) {
            addCriterion("bumenId <=", value, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidIn(List<Integer> values) {
            addCriterion("bumenId in", values, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidNotIn(List<Integer> values) {
            addCriterion("bumenId not in", values, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidBetween(Integer value1, Integer value2) {
            addCriterion("bumenId between", value1, value2, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumenidNotBetween(Integer value1, Integer value2) {
            addCriterion("bumenId not between", value1, value2, "bumenid");
            return (Criteria) this;
        }

        public Criteria andBumennameIsNull() {
            addCriterion("bumenName is null");
            return (Criteria) this;
        }

        public Criteria andBumennameIsNotNull() {
            addCriterion("bumenName is not null");
            return (Criteria) this;
        }

        public Criteria andBumennameEqualTo(String value) {
            addCriterion("bumenName =", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameNotEqualTo(String value) {
            addCriterion("bumenName <>", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameGreaterThan(String value) {
            addCriterion("bumenName >", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameGreaterThanOrEqualTo(String value) {
            addCriterion("bumenName >=", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameLessThan(String value) {
            addCriterion("bumenName <", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameLessThanOrEqualTo(String value) {
            addCriterion("bumenName <=", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameLike(String value) {
            addCriterion("bumenName like", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameNotLike(String value) {
            addCriterion("bumenName not like", value, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameIn(List<String> values) {
            addCriterion("bumenName in", values, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameNotIn(List<String> values) {
            addCriterion("bumenName not in", values, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameBetween(String value1, String value2) {
            addCriterion("bumenName between", value1, value2, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBumennameNotBetween(String value1, String value2) {
            addCriterion("bumenName not between", value1, value2, "bumenname");
            return (Criteria) this;
        }

        public Criteria andBuyuanidIsNull() {
            addCriterion("buyuanId is null");
            return (Criteria) this;
        }

        public Criteria andBuyuanidIsNotNull() {
            addCriterion("buyuanId is not null");
            return (Criteria) this;
        }

        public Criteria andBuyuanidEqualTo(Integer value) {
            addCriterion("buyuanId =", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidNotEqualTo(Integer value) {
            addCriterion("buyuanId <>", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidGreaterThan(Integer value) {
            addCriterion("buyuanId >", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyuanId >=", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidLessThan(Integer value) {
            addCriterion("buyuanId <", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidLessThanOrEqualTo(Integer value) {
            addCriterion("buyuanId <=", value, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidIn(List<Integer> values) {
            addCriterion("buyuanId in", values, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidNotIn(List<Integer> values) {
            addCriterion("buyuanId not in", values, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidBetween(Integer value1, Integer value2) {
            addCriterion("buyuanId between", value1, value2, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuanidNotBetween(Integer value1, Integer value2) {
            addCriterion("buyuanId not between", value1, value2, "buyuanid");
            return (Criteria) this;
        }

        public Criteria andBuyuannameIsNull() {
            addCriterion("buyuanName is null");
            return (Criteria) this;
        }

        public Criteria andBuyuannameIsNotNull() {
            addCriterion("buyuanName is not null");
            return (Criteria) this;
        }

        public Criteria andBuyuannameEqualTo(String value) {
            addCriterion("buyuanName =", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameNotEqualTo(String value) {
            addCriterion("buyuanName <>", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameGreaterThan(String value) {
            addCriterion("buyuanName >", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameGreaterThanOrEqualTo(String value) {
            addCriterion("buyuanName >=", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameLessThan(String value) {
            addCriterion("buyuanName <", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameLessThanOrEqualTo(String value) {
            addCriterion("buyuanName <=", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameLike(String value) {
            addCriterion("buyuanName like", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameNotLike(String value) {
            addCriterion("buyuanName not like", value, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameIn(List<String> values) {
            addCriterion("buyuanName in", values, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameNotIn(List<String> values) {
            addCriterion("buyuanName not in", values, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameBetween(String value1, String value2) {
            addCriterion("buyuanName between", value1, value2, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuyuannameNotBetween(String value1, String value2) {
            addCriterion("buyuanName not between", value1, value2, "buyuanname");
            return (Criteria) this;
        }

        public Criteria andBuzhiidIsNull() {
            addCriterion("buzhiId is null");
            return (Criteria) this;
        }

        public Criteria andBuzhiidIsNotNull() {
            addCriterion("buzhiId is not null");
            return (Criteria) this;
        }

        public Criteria andBuzhiidEqualTo(Integer value) {
            addCriterion("buzhiId =", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidNotEqualTo(Integer value) {
            addCriterion("buzhiId <>", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidGreaterThan(Integer value) {
            addCriterion("buzhiId >", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("buzhiId >=", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidLessThan(Integer value) {
            addCriterion("buzhiId <", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidLessThanOrEqualTo(Integer value) {
            addCriterion("buzhiId <=", value, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidIn(List<Integer> values) {
            addCriterion("buzhiId in", values, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidNotIn(List<Integer> values) {
            addCriterion("buzhiId not in", values, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidBetween(Integer value1, Integer value2) {
            addCriterion("buzhiId between", value1, value2, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhiidNotBetween(Integer value1, Integer value2) {
            addCriterion("buzhiId not between", value1, value2, "buzhiid");
            return (Criteria) this;
        }

        public Criteria andBuzhinameIsNull() {
            addCriterion("buzhiName is null");
            return (Criteria) this;
        }

        public Criteria andBuzhinameIsNotNull() {
            addCriterion("buzhiName is not null");
            return (Criteria) this;
        }

        public Criteria andBuzhinameEqualTo(String value) {
            addCriterion("buzhiName =", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameNotEqualTo(String value) {
            addCriterion("buzhiName <>", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameGreaterThan(String value) {
            addCriterion("buzhiName >", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameGreaterThanOrEqualTo(String value) {
            addCriterion("buzhiName >=", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameLessThan(String value) {
            addCriterion("buzhiName <", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameLessThanOrEqualTo(String value) {
            addCriterion("buzhiName <=", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameLike(String value) {
            addCriterion("buzhiName like", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameNotLike(String value) {
            addCriterion("buzhiName not like", value, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameIn(List<String> values) {
            addCriterion("buzhiName in", values, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameNotIn(List<String> values) {
            addCriterion("buzhiName not in", values, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameBetween(String value1, String value2) {
            addCriterion("buzhiName between", value1, value2, "buzhiname");
            return (Criteria) this;
        }

        public Criteria andBuzhinameNotBetween(String value1, String value2) {
            addCriterion("buzhiName not between", value1, value2, "buzhiname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge Thu May 20 10:15:44 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}