package edu.thn.ciom.pojo;

import java.io.Serializable;
import java.util.Date;

public class YongHuPojo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuPassword
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghupassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuXingming
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuxingming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuSex
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghusex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuAge
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuPhone
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMinzu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuminzu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghumark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghumark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghumark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghumark3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuMark4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghumark4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date yonghudate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date yonghudate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDate2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Date yonghudate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghutype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghutype1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghutype2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double yonghudouble;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double yonghudouble1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Double yonghudouble2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuzong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuzong1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yonghuzong2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yonghuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yonghuimgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer yhroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String yhrolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuzhiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuzhiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byumenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer byuyuanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String byuyuanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer bumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String bumenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buyuanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buyuanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private Integer buzhiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yonghu.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private String buzhiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuId
     *
     * @return the value of t_yonghu.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuid() {
        return yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuid(Integer yonghuid) {
        this.setYonghuid(yonghuid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuId
     *
     * @param yonghuid the value for t_yonghu.yonghuId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuid(Integer yonghuid) {
        this.yonghuid = yonghuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuName
     *
     * @return the value of t_yonghu.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuname() {
        return yonghuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuname(String yonghuname) {
        this.setYonghuname(yonghuname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuName
     *
     * @param yonghuname the value for t_yonghu.yonghuName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuname(String yonghuname) {
        this.yonghuname = yonghuname == null ? null : yonghuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuPassword
     *
     * @return the value of t_yonghu.yonghuPassword
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghupassword() {
        return yonghupassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghupassword(String yonghupassword) {
        this.setYonghupassword(yonghupassword);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuPassword
     *
     * @param yonghupassword the value for t_yonghu.yonghuPassword
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghupassword(String yonghupassword) {
        this.yonghupassword = yonghupassword == null ? null : yonghupassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuXingming
     *
     * @return the value of t_yonghu.yonghuXingming
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuxingming() {
        return yonghuxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuxingming(String yonghuxingming) {
        this.setYonghuxingming(yonghuxingming);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuXingming
     *
     * @param yonghuxingming the value for t_yonghu.yonghuXingming
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuxingming(String yonghuxingming) {
        this.yonghuxingming = yonghuxingming == null ? null : yonghuxingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuSex
     *
     * @return the value of t_yonghu.yonghuSex
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghusex() {
        return yonghusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghusex(Integer yonghusex) {
        this.setYonghusex(yonghusex);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuSex
     *
     * @param yonghusex the value for t_yonghu.yonghuSex
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghusex(Integer yonghusex) {
        this.yonghusex = yonghusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuAge
     *
     * @return the value of t_yonghu.yonghuAge
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuage() {
        return yonghuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuage(Integer yonghuage) {
        this.setYonghuage(yonghuage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuAge
     *
     * @param yonghuage the value for t_yonghu.yonghuAge
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuage(Integer yonghuage) {
        this.yonghuage = yonghuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuPhone
     *
     * @return the value of t_yonghu.yonghuPhone
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuphone() {
        return yonghuphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuphone(String yonghuphone) {
        this.setYonghuphone(yonghuphone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuPhone
     *
     * @param yonghuphone the value for t_yonghu.yonghuPhone
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuphone(String yonghuphone) {
        this.yonghuphone = yonghuphone == null ? null : yonghuphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMinzu
     *
     * @return the value of t_yonghu.yonghuMinzu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuminzu() {
        return yonghuminzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuminzu(String yonghuminzu) {
        this.setYonghuminzu(yonghuminzu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMinzu
     *
     * @param yonghuminzu the value for t_yonghu.yonghuMinzu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuminzu(String yonghuminzu) {
        this.yonghuminzu = yonghuminzu == null ? null : yonghuminzu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark
     *
     * @return the value of t_yonghu.yonghuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghumark() {
        return yonghumark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghumark(String yonghumark) {
        this.setYonghumark(yonghumark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark
     *
     * @param yonghumark the value for t_yonghu.yonghuMark
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghumark(String yonghumark) {
        this.yonghumark = yonghumark == null ? null : yonghumark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark1
     *
     * @return the value of t_yonghu.yonghuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghumark1() {
        return yonghumark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghumark1(String yonghumark1) {
        this.setYonghumark1(yonghumark1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark1
     *
     * @param yonghumark1 the value for t_yonghu.yonghuMark1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghumark1(String yonghumark1) {
        this.yonghumark1 = yonghumark1 == null ? null : yonghumark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark2
     *
     * @return the value of t_yonghu.yonghuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghumark2() {
        return yonghumark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghumark2(String yonghumark2) {
        this.setYonghumark2(yonghumark2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark2
     *
     * @param yonghumark2 the value for t_yonghu.yonghuMark2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghumark2(String yonghumark2) {
        this.yonghumark2 = yonghumark2 == null ? null : yonghumark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark3
     *
     * @return the value of t_yonghu.yonghuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghumark3() {
        return yonghumark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghumark3(String yonghumark3) {
        this.setYonghumark3(yonghumark3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark3
     *
     * @param yonghumark3 the value for t_yonghu.yonghuMark3
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghumark3(String yonghumark3) {
        this.yonghumark3 = yonghumark3 == null ? null : yonghumark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuMark4
     *
     * @return the value of t_yonghu.yonghuMark4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghumark4() {
        return yonghumark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghumark4(String yonghumark4) {
        this.setYonghumark4(yonghumark4);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuMark4
     *
     * @param yonghumark4 the value for t_yonghu.yonghuMark4
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghumark4(String yonghumark4) {
        this.yonghumark4 = yonghumark4 == null ? null : yonghumark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDate
     *
     * @return the value of t_yonghu.yonghuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getYonghudate() {
        return yonghudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudate(Date yonghudate) {
        this.setYonghudate(yonghudate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDate
     *
     * @param yonghudate the value for t_yonghu.yonghuDate
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudate(Date yonghudate) {
        this.yonghudate = yonghudate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDate1
     *
     * @return the value of t_yonghu.yonghuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getYonghudate1() {
        return yonghudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudate1(Date yonghudate1) {
        this.setYonghudate1(yonghudate1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDate1
     *
     * @param yonghudate1 the value for t_yonghu.yonghuDate1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudate1(Date yonghudate1) {
        this.yonghudate1 = yonghudate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDate2
     *
     * @return the value of t_yonghu.yonghuDate2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Date getYonghudate2() {
        return yonghudate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudate2(Date yonghudate2) {
        this.setYonghudate2(yonghudate2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDate2
     *
     * @param yonghudate2 the value for t_yonghu.yonghuDate2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudate2(Date yonghudate2) {
        this.yonghudate2 = yonghudate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuType
     *
     * @return the value of t_yonghu.yonghuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghutype() {
        return yonghutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghutype(Integer yonghutype) {
        this.setYonghutype(yonghutype);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuType
     *
     * @param yonghutype the value for t_yonghu.yonghuType
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghutype(Integer yonghutype) {
        this.yonghutype = yonghutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuType1
     *
     * @return the value of t_yonghu.yonghuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghutype1() {
        return yonghutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghutype1(Integer yonghutype1) {
        this.setYonghutype1(yonghutype1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuType1
     *
     * @param yonghutype1 the value for t_yonghu.yonghuType1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghutype1(Integer yonghutype1) {
        this.yonghutype1 = yonghutype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuType2
     *
     * @return the value of t_yonghu.yonghuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghutype2() {
        return yonghutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghutype2(Integer yonghutype2) {
        this.setYonghutype2(yonghutype2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuType2
     *
     * @param yonghutype2 the value for t_yonghu.yonghuType2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghutype2(Integer yonghutype2) {
        this.yonghutype2 = yonghutype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDouble
     *
     * @return the value of t_yonghu.yonghuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getYonghudouble() {
        return yonghudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudouble(Double yonghudouble) {
        this.setYonghudouble(yonghudouble);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDouble
     *
     * @param yonghudouble the value for t_yonghu.yonghuDouble
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudouble(Double yonghudouble) {
        this.yonghudouble = yonghudouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDouble1
     *
     * @return the value of t_yonghu.yonghuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getYonghudouble1() {
        return yonghudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudouble1(Double yonghudouble1) {
        this.setYonghudouble1(yonghudouble1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDouble1
     *
     * @param yonghudouble1 the value for t_yonghu.yonghuDouble1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudouble1(Double yonghudouble1) {
        this.yonghudouble1 = yonghudouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuDouble2
     *
     * @return the value of t_yonghu.yonghuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Double getYonghudouble2() {
        return yonghudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghudouble2(Double yonghudouble2) {
        this.setYonghudouble2(yonghudouble2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuDouble2
     *
     * @param yonghudouble2 the value for t_yonghu.yonghuDouble2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghudouble2(Double yonghudouble2) {
        this.yonghudouble2 = yonghudouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuZong
     *
     * @return the value of t_yonghu.yonghuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuzong() {
        return yonghuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuzong(Integer yonghuzong) {
        this.setYonghuzong(yonghuzong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuZong
     *
     * @param yonghuzong the value for t_yonghu.yonghuZong
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuzong(Integer yonghuzong) {
        this.yonghuzong = yonghuzong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuZong1
     *
     * @return the value of t_yonghu.yonghuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuzong1() {
        return yonghuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuzong1(Integer yonghuzong1) {
        this.setYonghuzong1(yonghuzong1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuZong1
     *
     * @param yonghuzong1 the value for t_yonghu.yonghuZong1
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuzong1(Integer yonghuzong1) {
        this.yonghuzong1 = yonghuzong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuZong2
     *
     * @return the value of t_yonghu.yonghuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYonghuzong2() {
        return yonghuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuzong2(Integer yonghuzong2) {
        this.setYonghuzong2(yonghuzong2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuZong2
     *
     * @param yonghuzong2 the value for t_yonghu.yonghuZong2
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuzong2(Integer yonghuzong2) {
        this.yonghuzong2 = yonghuzong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuImg
     *
     * @return the value of t_yonghu.yonghuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuimg() {
        return yonghuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuimg(String yonghuimg) {
        this.setYonghuimg(yonghuimg);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuImg
     *
     * @param yonghuimg the value for t_yonghu.yonghuImg
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuimg(String yonghuimg) {
        this.yonghuimg = yonghuimg == null ? null : yonghuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yonghuImgName
     *
     * @return the value of t_yonghu.yonghuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYonghuimgname() {
        return yonghuimgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYonghuimgname(String yonghuimgname) {
        this.setYonghuimgname(yonghuimgname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yonghuImgName
     *
     * @param yonghuimgname the value for t_yonghu.yonghuImgName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYonghuimgname(String yonghuimgname) {
        this.yonghuimgname = yonghuimgname == null ? null : yonghuimgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhroleId
     *
     * @return the value of t_yonghu.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getYhroleid() {
        return yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYhroleid(Integer yhroleid) {
        this.setYhroleid(yhroleid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhroleId
     *
     * @param yhroleid the value for t_yonghu.yhroleId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhroleid(Integer yhroleid) {
        this.yhroleid = yhroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.yhroleName
     *
     * @return the value of t_yonghu.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getYhrolename() {
        return yhrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withYhrolename(String yhrolename) {
        this.setYhrolename(yhrolename);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.yhroleName
     *
     * @param yhrolename the value for t_yonghu.yhroleName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setYhrolename(String yhrolename) {
        this.yhrolename = yhrolename == null ? null : yhrolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byuzhiId
     *
     * @return the value of t_yonghu.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuzhiid() {
        return byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByuzhiid(Integer byuzhiid) {
        this.setByuzhiid(byuzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byuzhiId
     *
     * @param byuzhiid the value for t_yonghu.byuzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiid(Integer byuzhiid) {
        this.byuzhiid = byuzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byuzhiName
     *
     * @return the value of t_yonghu.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuzhiname() {
        return byuzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByuzhiname(String byuzhiname) {
        this.setByuzhiname(byuzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byuzhiName
     *
     * @param byuzhiname the value for t_yonghu.byuzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuzhiname(String byuzhiname) {
        this.byuzhiname = byuzhiname == null ? null : byuzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byumenId
     *
     * @return the value of t_yonghu.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByumenid() {
        return byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByumenid(Integer byumenid) {
        this.setByumenid(byumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byumenId
     *
     * @param byumenid the value for t_yonghu.byumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenid(Integer byumenid) {
        this.byumenid = byumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byumenName
     *
     * @return the value of t_yonghu.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByumenname() {
        return byumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByumenname(String byumenname) {
        this.setByumenname(byumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byumenName
     *
     * @param byumenname the value for t_yonghu.byumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByumenname(String byumenname) {
        this.byumenname = byumenname == null ? null : byumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byuyuanId
     *
     * @return the value of t_yonghu.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getByuyuanid() {
        return byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByuyuanid(Integer byuyuanid) {
        this.setByuyuanid(byuyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byuyuanId
     *
     * @param byuyuanid the value for t_yonghu.byuyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanid(Integer byuyuanid) {
        this.byuyuanid = byuyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.byuyuanName
     *
     * @return the value of t_yonghu.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getByuyuanname() {
        return byuyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withByuyuanname(String byuyuanname) {
        this.setByuyuanname(byuyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.byuyuanName
     *
     * @param byuyuanname the value for t_yonghu.byuyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setByuyuanname(String byuyuanname) {
        this.byuyuanname = byuyuanname == null ? null : byuyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.userId
     *
     * @return the value of t_yonghu.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withUserid(Integer userid) {
        this.setUserid(userid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.userId
     *
     * @param userid the value for t_yonghu.userId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.userName
     *
     * @return the value of t_yonghu.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.userName
     *
     * @param username the value for t_yonghu.userName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.bumenId
     *
     * @return the value of t_yonghu.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBumenid(Integer bumenid) {
        this.setBumenid(bumenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.bumenId
     *
     * @param bumenid the value for t_yonghu.bumenId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.bumenName
     *
     * @return the value of t_yonghu.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBumenname() {
        return bumenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBumenname(String bumenname) {
        this.setBumenname(bumenname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.bumenName
     *
     * @param bumenname the value for t_yonghu.bumenName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBumenname(String bumenname) {
        this.bumenname = bumenname == null ? null : bumenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.buyuanId
     *
     * @return the value of t_yonghu.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuyuanid() {
        return buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBuyuanid(Integer buyuanid) {
        this.setBuyuanid(buyuanid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.buyuanId
     *
     * @param buyuanid the value for t_yonghu.buyuanId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanid(Integer buyuanid) {
        this.buyuanid = buyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.buyuanName
     *
     * @return the value of t_yonghu.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuyuanname() {
        return buyuanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBuyuanname(String buyuanname) {
        this.setBuyuanname(buyuanname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.buyuanName
     *
     * @param buyuanname the value for t_yonghu.buyuanName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuyuanname(String buyuanname) {
        this.buyuanname = buyuanname == null ? null : buyuanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.buzhiId
     *
     * @return the value of t_yonghu.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public Integer getBuzhiid() {
        return buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBuzhiid(Integer buzhiid) {
        this.setBuzhiid(buzhiid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.buzhiId
     *
     * @param buzhiid the value for t_yonghu.buzhiId
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiid(Integer buzhiid) {
        this.buzhiid = buzhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yonghu.buzhiName
     *
     * @return the value of t_yonghu.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public String getBuzhiname() {
        return buzhiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public YongHuPojo withBuzhiname(String buzhiname) {
        this.setBuzhiname(buzhiname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yonghu.buzhiName
     *
     * @param buzhiname the value for t_yonghu.buzhiName
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    public void setBuzhiname(String buzhiname) {
        this.buzhiname = buzhiname == null ? null : buzhiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", yonghuid=").append(yonghuid);
        sb.append(", yonghuname=").append(yonghuname);
        sb.append(", yonghupassword=").append(yonghupassword);
        sb.append(", yonghuxingming=").append(yonghuxingming);
        sb.append(", yonghusex=").append(yonghusex);
        sb.append(", yonghuage=").append(yonghuage);
        sb.append(", yonghuphone=").append(yonghuphone);
        sb.append(", yonghuminzu=").append(yonghuminzu);
        sb.append(", yonghumark=").append(yonghumark);
        sb.append(", yonghumark1=").append(yonghumark1);
        sb.append(", yonghumark2=").append(yonghumark2);
        sb.append(", yonghumark3=").append(yonghumark3);
        sb.append(", yonghumark4=").append(yonghumark4);
        sb.append(", yonghudate=").append(yonghudate);
        sb.append(", yonghudate1=").append(yonghudate1);
        sb.append(", yonghudate2=").append(yonghudate2);
        sb.append(", yonghutype=").append(yonghutype);
        sb.append(", yonghutype1=").append(yonghutype1);
        sb.append(", yonghutype2=").append(yonghutype2);
        sb.append(", yonghudouble=").append(yonghudouble);
        sb.append(", yonghudouble1=").append(yonghudouble1);
        sb.append(", yonghudouble2=").append(yonghudouble2);
        sb.append(", yonghuzong=").append(yonghuzong);
        sb.append(", yonghuzong1=").append(yonghuzong1);
        sb.append(", yonghuzong2=").append(yonghuzong2);
        sb.append(", yonghuimg=").append(yonghuimg);
        sb.append(", yonghuimgname=").append(yonghuimgname);
        sb.append(", yhroleid=").append(yhroleid);
        sb.append(", yhrolename=").append(yhrolename);
        sb.append(", byuzhiid=").append(byuzhiid);
        sb.append(", byuzhiname=").append(byuzhiname);
        sb.append(", byumenid=").append(byumenid);
        sb.append(", byumenname=").append(byumenname);
        sb.append(", byuyuanid=").append(byuyuanid);
        sb.append(", byuyuanname=").append(byuyuanname);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", bumenid=").append(bumenid);
        sb.append(", bumenname=").append(bumenname);
        sb.append(", buyuanid=").append(buyuanid);
        sb.append(", buyuanname=").append(buyuanname);
        sb.append(", buzhiid=").append(buzhiid);
        sb.append(", buzhiname=").append(buzhiname);
        sb.append("]");
        return sb.toString();
    }
}