package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.BiaotiPojo;
import edu.thn.ciom.pojo.BiaotiPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface BiaotiPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(BiaotiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(BiaotiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_jcbiaoti",
            "where jcbiaotiId = #{jcbiaotiid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer jcbiaotiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_jcbiaoti (jcbiaotiName, jcbiaotiNeirong, ",
            "jcbiaotiMark, jcbiaotiMark1, ",
            "jcbiaotiMark2, jcbiaotiPaixu, ",
            "jcbiaotiType, jcbiaotiType1, ",
            "jcbiaotiType2)",
            "values (#{jcbiaotiname,jdbcType=VARCHAR}, #{jcbiaotineirong,jdbcType=VARCHAR}, ",
            "#{jcbiaotimark,jdbcType=VARCHAR}, #{jcbiaotimark1,jdbcType=VARCHAR}, ",
            "#{jcbiaotimark2,jdbcType=VARCHAR}, #{jcbiaotipaixu,jdbcType=INTEGER}, ",
            "#{jcbiaotitype,jdbcType=INTEGER}, #{jcbiaotitype1,jdbcType=INTEGER}, ",
            "#{jcbiaotitype2,jdbcType=INTEGER})"
    })
    @SelectKey(statement = "CALL IDENTITY()", keyProperty = "jcbiaotiid", before = false, resultType = Integer.class)
    int insert(BiaotiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(BiaotiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<BiaotiPojo> selectByExampleWithRowbounds(BiaotiPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<BiaotiPojo> selectByExample(BiaotiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "jcbiaotiId, jcbiaotiName, jcbiaotiNeirong, jcbiaotiMark, jcbiaotiMark1, jcbiaotiMark2, ",
            "jcbiaotiPaixu, jcbiaotiType, jcbiaotiType1, jcbiaotiType2",
            "from t_jcbiaoti",
            "where jcbiaotiId = #{jcbiaotiid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.BiaotiPojoMapper.BaseResultMap")
    BiaotiPojo selectByPrimaryKey(Integer jcbiaotiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") BiaotiPojo record, @Param("example") BiaotiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") BiaotiPojo record, @Param("example") BiaotiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(BiaotiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcbiaoti
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_jcbiaoti",
            "set jcbiaotiName = #{jcbiaotiname,jdbcType=VARCHAR},",
            "jcbiaotiNeirong = #{jcbiaotineirong,jdbcType=VARCHAR},",
            "jcbiaotiMark = #{jcbiaotimark,jdbcType=VARCHAR},",
            "jcbiaotiMark1 = #{jcbiaotimark1,jdbcType=VARCHAR},",
            "jcbiaotiMark2 = #{jcbiaotimark2,jdbcType=VARCHAR},",
            "jcbiaotiPaixu = #{jcbiaotipaixu,jdbcType=INTEGER},",
            "jcbiaotiType = #{jcbiaotitype,jdbcType=INTEGER},",
            "jcbiaotiType1 = #{jcbiaotitype1,jdbcType=INTEGER},",
            "jcbiaotiType2 = #{jcbiaotitype2,jdbcType=INTEGER}",
            "where jcbiaotiId = #{jcbiaotiid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BiaotiPojo record);
}