package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.DaohangPojo;
import edu.thn.ciom.pojo.DaohangPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface DaohangPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(DaohangPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(DaohangPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_jcdaohang",
            "where jcdaohangId = #{jcdaohangid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer jcdaohangid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_jcdaohang (jcdaohangName, jcdaohangNeirong, ",
            "jcdaohangMark, jcdaohangMark1, ",
            "jcdaohangMark2, jcdaohangPaixu, ",
            "jcdaohangType, jcdaohangType1, ",
            "jcdaohangType2, jcbiaotiId, ",
            "jcbiaotiName)",
            "values (#{jcdaohangname,jdbcType=VARCHAR}, #{jcdaohangneirong,jdbcType=VARCHAR}, ",
            "#{jcdaohangmark,jdbcType=VARCHAR}, #{jcdaohangmark1,jdbcType=VARCHAR}, ",
            "#{jcdaohangmark2,jdbcType=VARCHAR}, #{jcdaohangpaixu,jdbcType=INTEGER}, ",
            "#{jcdaohangtype,jdbcType=INTEGER}, #{jcdaohangtype1,jdbcType=INTEGER}, ",
            "#{jcdaohangtype2,jdbcType=INTEGER}, #{jcbiaotiid,jdbcType=INTEGER}, ",
            "#{jcbiaotiname,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "CALL IDENTITY()", keyProperty = "jcdaohangid", before = false, resultType = Integer.class)
    int insert(DaohangPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(DaohangPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<DaohangPojo> selectByExampleWithRowbounds(DaohangPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<DaohangPojo> selectByExample(DaohangPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "jcdaohangId, jcdaohangName, jcdaohangNeirong, jcdaohangMark, jcdaohangMark1, ",
            "jcdaohangMark2, jcdaohangPaixu, jcdaohangType, jcdaohangType1, jcdaohangType2, ",
            "jcbiaotiId, jcbiaotiName",
            "from t_jcdaohang",
            "where jcdaohangId = #{jcdaohangid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.DaohangPojoMapper.BaseResultMap")
    DaohangPojo selectByPrimaryKey(Integer jcdaohangid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") DaohangPojo record, @Param("example") DaohangPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") DaohangPojo record, @Param("example") DaohangPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(DaohangPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_jcdaohang",
            "set jcdaohangName = #{jcdaohangname,jdbcType=VARCHAR},",
            "jcdaohangNeirong = #{jcdaohangneirong,jdbcType=VARCHAR},",
            "jcdaohangMark = #{jcdaohangmark,jdbcType=VARCHAR},",
            "jcdaohangMark1 = #{jcdaohangmark1,jdbcType=VARCHAR},",
            "jcdaohangMark2 = #{jcdaohangmark2,jdbcType=VARCHAR},",
            "jcdaohangPaixu = #{jcdaohangpaixu,jdbcType=INTEGER},",
            "jcdaohangType = #{jcdaohangtype,jdbcType=INTEGER},",
            "jcdaohangType1 = #{jcdaohangtype1,jdbcType=INTEGER},",
            "jcdaohangType2 = #{jcdaohangtype2,jdbcType=INTEGER},",
            "jcbiaotiId = #{jcbiaotiid,jdbcType=INTEGER},",
            "jcbiaotiName = #{jcbiaotiname,jdbcType=VARCHAR}",
            "where jcdaohangId = #{jcdaohangid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DaohangPojo record);
}