package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.DuochuPojo;
import edu.thn.ciom.pojo.DuochuPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface DuochuPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(DuochuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(DuochuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_sjduochu",
            "where sjduochuId = #{sjduochuid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sjduochuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_sjduochu (sjduochuName, sjduochuMark, ",
            "sjduochuMark1, sjduochuMark2, ",
            "sjduochuMark3, sjduochuDate, ",
            "sjduochuDate1, sjduochuZong, ",
            "sjduochuZong1, sjduochuZong2, ",
            "sjduochuDouble, sjduochuDouble1, ",
            "sjduochuDouble2, sjduochuType, ",
            "sjduochuType1, sjduochuType2, ",
            "sjqitaId, sjqitaName, ",
            "sjlaiyuanId, sjlaiyuanName, ",
            "sjduochuImg, sjduochuImgName, ",
            "shujuId, shujuName, ",
            "sjleixingId, sjleixingName, ",
            "sjxingtaiId, sjxingtaiName, ",
            "userId, userName, ",
            "bumenId, bumenName, ",
            "buyuanId, buyuanName, ",
            "yonghuId, yonghuName, ",
            "byumenId, byumenName, ",
            "byuyuanId, byuyuanName, ",
            "buzhiId, buzhiName, ",
            "roleId, roleName, ",
            "byuzhiId, byuzhiName, ",
            "yhroleId, yhroleName)",
            "values (#{sjduochuname,jdbcType=VARCHAR}, #{sjduochumark,jdbcType=VARCHAR}, ",
            "#{sjduochumark1,jdbcType=VARCHAR}, #{sjduochumark2,jdbcType=VARCHAR}, ",
            "#{sjduochumark3,jdbcType=VARCHAR}, #{sjduochudate,jdbcType=TIMESTAMP}, ",
            "#{sjduochudate1,jdbcType=TIMESTAMP}, #{sjduochuzong,jdbcType=INTEGER}, ",
            "#{sjduochuzong1,jdbcType=INTEGER}, #{sjduochuzong2,jdbcType=INTEGER}, ",
            "#{sjduochudouble,jdbcType=DOUBLE}, #{sjduochudouble1,jdbcType=DOUBLE}, ",
            "#{sjduochudouble2,jdbcType=DOUBLE}, #{sjduochutype,jdbcType=INTEGER}, ",
            "#{sjduochutype1,jdbcType=INTEGER}, #{sjduochutype2,jdbcType=INTEGER}, ",
            "#{sjqitaid,jdbcType=INTEGER}, #{sjqitaname,jdbcType=VARCHAR}, ",
            "#{sjlaiyuanid,jdbcType=INTEGER}, #{sjlaiyuanname,jdbcType=VARCHAR}, ",
            "#{sjduochuimg,jdbcType=VARCHAR}, #{sjduochuimgname,jdbcType=VARCHAR}, ",
            "#{shujuid,jdbcType=INTEGER}, #{shujuname,jdbcType=VARCHAR}, ",
            "#{sjleixingid,jdbcType=INTEGER}, #{sjleixingname,jdbcType=VARCHAR}, ",
            "#{sjxingtaiid,jdbcType=INTEGER}, #{sjxingtainame,jdbcType=VARCHAR}, ",
            "#{userid,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
            "#{bumenid,jdbcType=INTEGER}, #{bumenname,jdbcType=VARCHAR}, ",
            "#{buyuanid,jdbcType=INTEGER}, #{buyuanname,jdbcType=VARCHAR}, ",
            "#{yonghuid,jdbcType=INTEGER}, #{yonghuname,jdbcType=VARCHAR}, ",
            "#{byumenid,jdbcType=INTEGER}, #{byumenname,jdbcType=VARCHAR}, ",
            "#{byuyuanid,jdbcType=INTEGER}, #{byuyuanname,jdbcType=VARCHAR}, ",
            "#{buzhiid,jdbcType=INTEGER}, #{buzhiname,jdbcType=VARCHAR}, ",
            "#{roleid,jdbcType=INTEGER}, #{rolename,jdbcType=VARCHAR}, ",
            "#{byuzhiid,jdbcType=INTEGER}, #{byuzhiname,jdbcType=VARCHAR}, ",
            "#{yhroleid,jdbcType=INTEGER}, #{yhrolename,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "CALL IDENTITY()", keyProperty = "sjduochuid", before = false, resultType = Integer.class)
    int insert(DuochuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(DuochuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<DuochuPojo> selectByExampleWithRowbounds(DuochuPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<DuochuPojo> selectByExample(DuochuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "sjduochuId, sjduochuName, sjduochuMark, sjduochuMark1, sjduochuMark2, sjduochuMark3, ",
            "sjduochuDate, sjduochuDate1, sjduochuZong, sjduochuZong1, sjduochuZong2, sjduochuDouble, ",
            "sjduochuDouble1, sjduochuDouble2, sjduochuType, sjduochuType1, sjduochuType2, ",
            "sjqitaId, sjqitaName, sjlaiyuanId, sjlaiyuanName, sjduochuImg, sjduochuImgName, ",
            "shujuId, shujuName, sjleixingId, sjleixingName, sjxingtaiId, sjxingtaiName, ",
            "userId, userName, bumenId, bumenName, buyuanId, buyuanName, yonghuId, yonghuName, ",
            "byumenId, byumenName, byuyuanId, byuyuanName, buzhiId, buzhiName, roleId, roleName, ",
            "byuzhiId, byuzhiName, yhroleId, yhroleName",
            "from t_sjduochu",
            "where sjduochuId = #{sjduochuid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.DuochuPojoMapper.BaseResultMap")
    DuochuPojo selectByPrimaryKey(Integer sjduochuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") DuochuPojo record, @Param("example") DuochuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") DuochuPojo record, @Param("example") DuochuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(DuochuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjduochu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_sjduochu",
            "set sjduochuName = #{sjduochuname,jdbcType=VARCHAR},",
            "sjduochuMark = #{sjduochumark,jdbcType=VARCHAR},",
            "sjduochuMark1 = #{sjduochumark1,jdbcType=VARCHAR},",
            "sjduochuMark2 = #{sjduochumark2,jdbcType=VARCHAR},",
            "sjduochuMark3 = #{sjduochumark3,jdbcType=VARCHAR},",
            "sjduochuDate = #{sjduochudate,jdbcType=TIMESTAMP},",
            "sjduochuDate1 = #{sjduochudate1,jdbcType=TIMESTAMP},",
            "sjduochuZong = #{sjduochuzong,jdbcType=INTEGER},",
            "sjduochuZong1 = #{sjduochuzong1,jdbcType=INTEGER},",
            "sjduochuZong2 = #{sjduochuzong2,jdbcType=INTEGER},",
            "sjduochuDouble = #{sjduochudouble,jdbcType=DOUBLE},",
            "sjduochuDouble1 = #{sjduochudouble1,jdbcType=DOUBLE},",
            "sjduochuDouble2 = #{sjduochudouble2,jdbcType=DOUBLE},",
            "sjduochuType = #{sjduochutype,jdbcType=INTEGER},",
            "sjduochuType1 = #{sjduochutype1,jdbcType=INTEGER},",
            "sjduochuType2 = #{sjduochutype2,jdbcType=INTEGER},",
            "sjqitaId = #{sjqitaid,jdbcType=INTEGER},",
            "sjqitaName = #{sjqitaname,jdbcType=VARCHAR},",
            "sjlaiyuanId = #{sjlaiyuanid,jdbcType=INTEGER},",
            "sjlaiyuanName = #{sjlaiyuanname,jdbcType=VARCHAR},",
            "sjduochuImg = #{sjduochuimg,jdbcType=VARCHAR},",
            "sjduochuImgName = #{sjduochuimgname,jdbcType=VARCHAR},",
            "shujuId = #{shujuid,jdbcType=INTEGER},",
            "shujuName = #{shujuname,jdbcType=VARCHAR},",
            "sjleixingId = #{sjleixingid,jdbcType=INTEGER},",
            "sjleixingName = #{sjleixingname,jdbcType=VARCHAR},",
            "sjxingtaiId = #{sjxingtaiid,jdbcType=INTEGER},",
            "sjxingtaiName = #{sjxingtainame,jdbcType=VARCHAR},",
            "userId = #{userid,jdbcType=INTEGER},",
            "userName = #{username,jdbcType=VARCHAR},",
            "bumenId = #{bumenid,jdbcType=INTEGER},",
            "bumenName = #{bumenname,jdbcType=VARCHAR},",
            "buyuanId = #{buyuanid,jdbcType=INTEGER},",
            "buyuanName = #{buyuanname,jdbcType=VARCHAR},",
            "yonghuId = #{yonghuid,jdbcType=INTEGER},",
            "yonghuName = #{yonghuname,jdbcType=VARCHAR},",
            "byumenId = #{byumenid,jdbcType=INTEGER},",
            "byumenName = #{byumenname,jdbcType=VARCHAR},",
            "byuyuanId = #{byuyuanid,jdbcType=INTEGER},",
            "byuyuanName = #{byuyuanname,jdbcType=VARCHAR},",
            "buzhiId = #{buzhiid,jdbcType=INTEGER},",
            "buzhiName = #{buzhiname,jdbcType=VARCHAR},",
            "roleId = #{roleid,jdbcType=INTEGER},",
            "roleName = #{rolename,jdbcType=VARCHAR},",
            "byuzhiId = #{byuzhiid,jdbcType=INTEGER},",
            "byuzhiName = #{byuzhiname,jdbcType=VARCHAR},",
            "yhroleId = #{yhroleid,jdbcType=INTEGER},",
            "yhroleName = #{yhrolename,jdbcType=VARCHAR}",
            "where sjduochuId = #{sjduochuid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DuochuPojo record);
}