package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.JianChuPojo;
import edu.thn.ciom.pojo.JianChuPojoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface JianChuPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(JianChuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(JianChuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
        "delete from t_sjjianchu",
        "where sjjianchuId = #{sjjianchuid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sjjianchuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
        "insert into t_sjjianchu (sjjianchuName, sjjianchuMark, ",
        "sjjianchuMark1, sjjianchuMark2, ",
        "sjjianchuMark3, sjjianchuDate, ",
        "sjjianchuDate1, sjjianchuZong, ",
        "sjjianchuZong1, sjjianchuZong2, ",
        "sjjianchuDouble, sjjianchuDouble1, ",
        "sjjianchuDouble2, sjjianchuType, ",
        "sjjianchuType1, sjjianchuType2, ",
        "sjqitaId, sjqitaName, ",
        "sjlaiyuanId, sjlaiyuanName, ",
        "sjjianchuImg, sjjianchuImgName, ",
        "shujuId, shujuName, ",
        "sjleixingId, sjleixingName, ",
        "sjxingtaiId, sjxingtaiName, ",
        "userId, userName, ",
        "bumenId, bumenName, ",
        "buyuanId, buyuanName, ",
        "yonghuId, yonghuName, ",
        "byumenId, byumenName, ",
        "byuyuanId, byuyuanName, ",
        "buzhiId, buzhiName, ",
        "roleId, roleName, ",
        "byuzhiId, byuzhiName, ",
        "yhroleId, yhroleName)",
        "values (#{sjjianchuname,jdbcType=VARCHAR}, #{sjjianchumark,jdbcType=VARCHAR}, ",
        "#{sjjianchumark1,jdbcType=VARCHAR}, #{sjjianchumark2,jdbcType=VARCHAR}, ",
        "#{sjjianchumark3,jdbcType=VARCHAR}, #{sjjianchudate,jdbcType=TIMESTAMP}, ",
        "#{sjjianchudate1,jdbcType=TIMESTAMP}, #{sjjianchuzong,jdbcType=INTEGER}, ",
        "#{sjjianchuzong1,jdbcType=INTEGER}, #{sjjianchuzong2,jdbcType=INTEGER}, ",
        "#{sjjianchudouble,jdbcType=DOUBLE}, #{sjjianchudouble1,jdbcType=DOUBLE}, ",
        "#{sjjianchudouble2,jdbcType=DOUBLE}, #{sjjianchutype,jdbcType=INTEGER}, ",
        "#{sjjianchutype1,jdbcType=INTEGER}, #{sjjianchutype2,jdbcType=INTEGER}, ",
        "#{sjqitaid,jdbcType=INTEGER}, #{sjqitaname,jdbcType=VARCHAR}, ",
        "#{sjlaiyuanid,jdbcType=INTEGER}, #{sjlaiyuanname,jdbcType=VARCHAR}, ",
        "#{sjjianchuimg,jdbcType=VARCHAR}, #{sjjianchuimgname,jdbcType=VARCHAR}, ",
        "#{shujuid,jdbcType=INTEGER}, #{shujuname,jdbcType=VARCHAR}, ",
        "#{sjleixingid,jdbcType=INTEGER}, #{sjleixingname,jdbcType=VARCHAR}, ",
        "#{sjxingtaiid,jdbcType=INTEGER}, #{sjxingtainame,jdbcType=VARCHAR}, ",
        "#{userid,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{bumenid,jdbcType=INTEGER}, #{bumenname,jdbcType=VARCHAR}, ",
        "#{buyuanid,jdbcType=INTEGER}, #{buyuanname,jdbcType=VARCHAR}, ",
        "#{yonghuid,jdbcType=INTEGER}, #{yonghuname,jdbcType=VARCHAR}, ",
        "#{byumenid,jdbcType=INTEGER}, #{byumenname,jdbcType=VARCHAR}, ",
        "#{byuyuanid,jdbcType=INTEGER}, #{byuyuanname,jdbcType=VARCHAR}, ",
        "#{buzhiid,jdbcType=INTEGER}, #{buzhiname,jdbcType=VARCHAR}, ",
        "#{roleid,jdbcType=INTEGER}, #{rolename,jdbcType=VARCHAR}, ",
        "#{byuzhiid,jdbcType=INTEGER}, #{byuzhiname,jdbcType=VARCHAR}, ",
        "#{yhroleid,jdbcType=INTEGER}, #{yhrolename,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="sjjianchuid", before=false, resultType=Integer.class)
    int insert(JianChuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(JianChuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<JianChuPojo> selectByExampleWithRowbounds(JianChuPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<JianChuPojo> selectByExample(JianChuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
        "select",
        "sjjianchuId, sjjianchuName, sjjianchuMark, sjjianchuMark1, sjjianchuMark2, sjjianchuMark3, ",
        "sjjianchuDate, sjjianchuDate1, sjjianchuZong, sjjianchuZong1, sjjianchuZong2, ",
        "sjjianchuDouble, sjjianchuDouble1, sjjianchuDouble2, sjjianchuType, sjjianchuType1, ",
        "sjjianchuType2, sjqitaId, sjqitaName, sjlaiyuanId, sjlaiyuanName, sjjianchuImg, ",
        "sjjianchuImgName, shujuId, shujuName, sjleixingId, sjleixingName, sjxingtaiId, ",
        "sjxingtaiName, userId, userName, bumenId, bumenName, buyuanId, buyuanName, yonghuId, ",
        "yonghuName, byumenId, byumenName, byuyuanId, byuyuanName, buzhiId, buzhiName, ",
        "roleId, roleName, byuzhiId, byuzhiName, yhroleId, yhroleName",
        "from t_sjjianchu",
        "where sjjianchuId = #{sjjianchuid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.JianChuPojoMapper.BaseResultMap")
    JianChuPojo selectByPrimaryKey(Integer sjjianchuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") JianChuPojo record, @Param("example") JianChuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") JianChuPojo record, @Param("example") JianChuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(JianChuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjjianchu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
        "update t_sjjianchu",
        "set sjjianchuName = #{sjjianchuname,jdbcType=VARCHAR},",
          "sjjianchuMark = #{sjjianchumark,jdbcType=VARCHAR},",
          "sjjianchuMark1 = #{sjjianchumark1,jdbcType=VARCHAR},",
          "sjjianchuMark2 = #{sjjianchumark2,jdbcType=VARCHAR},",
          "sjjianchuMark3 = #{sjjianchumark3,jdbcType=VARCHAR},",
          "sjjianchuDate = #{sjjianchudate,jdbcType=TIMESTAMP},",
          "sjjianchuDate1 = #{sjjianchudate1,jdbcType=TIMESTAMP},",
          "sjjianchuZong = #{sjjianchuzong,jdbcType=INTEGER},",
          "sjjianchuZong1 = #{sjjianchuzong1,jdbcType=INTEGER},",
          "sjjianchuZong2 = #{sjjianchuzong2,jdbcType=INTEGER},",
          "sjjianchuDouble = #{sjjianchudouble,jdbcType=DOUBLE},",
          "sjjianchuDouble1 = #{sjjianchudouble1,jdbcType=DOUBLE},",
          "sjjianchuDouble2 = #{sjjianchudouble2,jdbcType=DOUBLE},",
          "sjjianchuType = #{sjjianchutype,jdbcType=INTEGER},",
          "sjjianchuType1 = #{sjjianchutype1,jdbcType=INTEGER},",
          "sjjianchuType2 = #{sjjianchutype2,jdbcType=INTEGER},",
          "sjqitaId = #{sjqitaid,jdbcType=INTEGER},",
          "sjqitaName = #{sjqitaname,jdbcType=VARCHAR},",
          "sjlaiyuanId = #{sjlaiyuanid,jdbcType=INTEGER},",
          "sjlaiyuanName = #{sjlaiyuanname,jdbcType=VARCHAR},",
          "sjjianchuImg = #{sjjianchuimg,jdbcType=VARCHAR},",
          "sjjianchuImgName = #{sjjianchuimgname,jdbcType=VARCHAR},",
          "shujuId = #{shujuid,jdbcType=INTEGER},",
          "shujuName = #{shujuname,jdbcType=VARCHAR},",
          "sjleixingId = #{sjleixingid,jdbcType=INTEGER},",
          "sjleixingName = #{sjleixingname,jdbcType=VARCHAR},",
          "sjxingtaiId = #{sjxingtaiid,jdbcType=INTEGER},",
          "sjxingtaiName = #{sjxingtainame,jdbcType=VARCHAR},",
          "userId = #{userid,jdbcType=INTEGER},",
          "userName = #{username,jdbcType=VARCHAR},",
          "bumenId = #{bumenid,jdbcType=INTEGER},",
          "bumenName = #{bumenname,jdbcType=VARCHAR},",
          "buyuanId = #{buyuanid,jdbcType=INTEGER},",
          "buyuanName = #{buyuanname,jdbcType=VARCHAR},",
          "yonghuId = #{yonghuid,jdbcType=INTEGER},",
          "yonghuName = #{yonghuname,jdbcType=VARCHAR},",
          "byumenId = #{byumenid,jdbcType=INTEGER},",
          "byumenName = #{byumenname,jdbcType=VARCHAR},",
          "byuyuanId = #{byuyuanid,jdbcType=INTEGER},",
          "byuyuanName = #{byuyuanname,jdbcType=VARCHAR},",
          "buzhiId = #{buzhiid,jdbcType=INTEGER},",
          "buzhiName = #{buzhiname,jdbcType=VARCHAR},",
          "roleId = #{roleid,jdbcType=INTEGER},",
          "roleName = #{rolename,jdbcType=VARCHAR},",
          "byuzhiId = #{byuzhiid,jdbcType=INTEGER},",
          "byuzhiName = #{byuzhiname,jdbcType=VARCHAR},",
          "yhroleId = #{yhroleid,jdbcType=INTEGER},",
          "yhroleName = #{yhrolename,jdbcType=VARCHAR}",
        "where sjjianchuId = #{sjjianchuid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JianChuPojo record);
}