package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.RizhiPojo;
import edu.thn.ciom.pojo.RizhiPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
// import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface RizhiPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(RizhiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(RizhiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_rizhi",
            "where rizhiId = #{rizhiid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer rizhiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_rizhi (rizhiName, dengluIp, date)",
            "values (#{rizhiname,jdbcType=VARCHAR}, #{dengluip,jdbcType=VARCHAR}, CURRENT_TIMESTAMP())"
            //"#{date,jdbcType=TIMESTAMP})"
    })
//    @SelectKey(statement="CALL IDENTITY()", keyProperty="rizhiid", before=false, resultType=Integer.class)
    int insert(RizhiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(RizhiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<RizhiPojo> selectByExampleWithRowbounds(RizhiPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<RizhiPojo> selectByExample(RizhiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "rizhiId, rizhiName, dengluIp, date",
            "from t_rizhi",
            "where rizhiId = #{rizhiid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.RizhiPojoMapper.BaseResultMap")
    RizhiPojo selectByPrimaryKey(Integer rizhiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") RizhiPojo record, @Param("example") RizhiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") RizhiPojo record, @Param("example") RizhiPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(RizhiPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rizhi
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_rizhi",
            "set rizhiName = #{rizhiname,jdbcType=VARCHAR},",
            "dengluIp = #{dengluip,jdbcType=VARCHAR},",
            "date = #{date,jdbcType=TIMESTAMP}",
            "where rizhiId = #{rizhiid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RizhiPojo record);
}