package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.UserPojo;
import edu.thn.ciom.pojo.UserPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface UserPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(UserPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(UserPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_user",
            "where userId = #{userid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_user (userName, userPassword, ",
            "userXingming, userSex, ",
            "userAge, userMinzu, ",
            "userPhone, userMark, ",
            "userMark1, userMark2, ",
            "userMark3, userMark4, ",
            "userDate, userDate1, userDate2, ",
            "userType, userType1, ",
            "userType2, userDouble, ",
            "userDouble1, userDouble2, ",
            "userZong, userZong1, ",
            "userZong2, userImg, ",
            "userImgName, roleId, ",
            "roleName, bumenId, ",
            "bumenName, buyuanId, ",
            "buyuanName, buzhiId, ",
            "buzhiName)",
            "values (#{username,jdbcType=VARCHAR}, #{userpassword,jdbcType=VARCHAR}, ",
            "#{userxingming,jdbcType=VARCHAR}, #{usersex,jdbcType=INTEGER}, ",
            "#{userage,jdbcType=INTEGER}, #{userminzu,jdbcType=VARCHAR}, ",
            "#{userphone,jdbcType=VARCHAR}, #{usermark,jdbcType=VARCHAR}, ",
            "#{usermark1,jdbcType=VARCHAR}, #{usermark2,jdbcType=VARCHAR}, ",
            "#{usermark3,jdbcType=VARCHAR}, #{usermark4,jdbcType=VARCHAR}, ",
            "#{userdate,jdbcType=DATE}, #{userdate1,jdbcType=DATE}, #{userdate2,jdbcType=DATE}, ",
            "#{usertype,jdbcType=INTEGER}, #{usertype1,jdbcType=INTEGER}, ",
            "#{usertype2,jdbcType=INTEGER}, #{userdouble,jdbcType=DOUBLE}, ",
            "#{userdouble1,jdbcType=DOUBLE}, #{userdouble2,jdbcType=DOUBLE}, ",
            "#{userzong,jdbcType=INTEGER}, #{userzong1,jdbcType=INTEGER}, ",
            "#{userzong2,jdbcType=INTEGER}, #{userimg,jdbcType=VARCHAR}, ",
            "#{userimgname,jdbcType=VARCHAR}, #{roleid,jdbcType=INTEGER}, ",
            "#{rolename,jdbcType=VARCHAR}, #{bumenid,jdbcType=INTEGER}, ",
            "#{bumenname,jdbcType=VARCHAR}, #{buyuanid,jdbcType=INTEGER}, ",
            "#{buyuanname,jdbcType=VARCHAR}, #{buzhiid,jdbcType=INTEGER}, ",
            "#{buzhiname,jdbcType=VARCHAR})"
    })
    //statement="CALL IDENTITY()",
    //@SelectKey(useGeneratedKeys="true", keyProperty="userid", before=false, resultType=Integer.class)
    int insert(UserPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(UserPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<UserPojo> selectByExampleWithRowbounds(UserPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<UserPojo> selectByExample(UserPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "userId, userName, userPassword, userXingming, userSex, userAge, userMinzu, userPhone, ",
            "userMark, userMark1, userMark2, userMark3, userMark4, userDate, userDate1, userDate2, ",
            "userType, userType1, userType2, userDouble, userDouble1, userDouble2, userZong, ",
            "userZong1, userZong2, userImg, userImgName, roleId, roleName, bumenId, bumenName, ",
            "buyuanId, buyuanName, buzhiId, buzhiName",
            "from t_user",
            "where userId = #{userid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.UserPojoMapper.BaseResultMap")
    UserPojo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserPojo record, @Param("example") UserPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") UserPojo record, @Param("example") UserPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(UserPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_user",
            "set userName = #{username,jdbcType=VARCHAR},",
            "userPassword = #{userpassword,jdbcType=VARCHAR},",
            "userXingming = #{userxingming,jdbcType=VARCHAR},",
            "userSex = #{usersex,jdbcType=INTEGER},",
            "userAge = #{userage,jdbcType=INTEGER},",
            "userMinzu = #{userminzu,jdbcType=VARCHAR},",
            "userPhone = #{userphone,jdbcType=VARCHAR},",
            "userMark = #{usermark,jdbcType=VARCHAR},",
            "userMark1 = #{usermark1,jdbcType=VARCHAR},",
            "userMark2 = #{usermark2,jdbcType=VARCHAR},",
            "userMark3 = #{usermark3,jdbcType=VARCHAR},",
            "userMark4 = #{usermark4,jdbcType=VARCHAR},",
            "userDate = #{userdate,jdbcType=DATE},",
            "userDate1 = #{userdate1,jdbcType=DATE},",
            "userDate2 = #{userdate2,jdbcType=DATE},",
            "userType = #{usertype,jdbcType=INTEGER},",
            "userType1 = #{usertype1,jdbcType=INTEGER},",
            "userType2 = #{usertype2,jdbcType=INTEGER},",
            "userDouble = #{userdouble,jdbcType=DOUBLE},",
            "userDouble1 = #{userdouble1,jdbcType=DOUBLE},",
            "userDouble2 = #{userdouble2,jdbcType=DOUBLE},",
            "userZong = #{userzong,jdbcType=INTEGER},",
            "userZong1 = #{userzong1,jdbcType=INTEGER},",
            "userZong2 = #{userzong2,jdbcType=INTEGER},",
            "userImg = #{userimg,jdbcType=VARCHAR},",
            "userImgName = #{userimgname,jdbcType=VARCHAR},",
            "roleId = #{roleid,jdbcType=INTEGER},",
            "roleName = #{rolename,jdbcType=VARCHAR},",
            "bumenId = #{bumenid,jdbcType=INTEGER},",
            "bumenName = #{bumenname,jdbcType=VARCHAR},",
            "buyuanId = #{buyuanid,jdbcType=INTEGER},",
            "buyuanName = #{buyuanname,jdbcType=VARCHAR},",
            "buzhiId = #{buzhiid,jdbcType=INTEGER},",
            "buzhiName = #{buzhiname,jdbcType=VARCHAR}",
            "where userId = #{userid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserPojo record);
}