package edu.thn.ciom.dao;

import edu.thn.ciom.pojo.YongHuPojo;
import edu.thn.ciom.pojo.YongHuPojoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface YongHuPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    long countByExample(YongHuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int deleteByExample(YongHuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Delete({
            "delete from t_yonghu",
            "where yonghuId = #{yonghuid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer yonghuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Insert({
            "insert into t_yonghu (yonghuName, yonghuPassword, ",
            "yonghuXingming, yonghuSex, ",
            "yonghuAge, yonghuPhone, ",
            "yonghuMinzu, yonghuMark, ",
            "yonghuMark1, yonghuMark2, ",
            "yonghuMark3, yonghuMark4, ",
            "yonghuDate, yonghuDate1, ",
            "yonghuDate2, yonghuType, ",
            "yonghuType1, yonghuType2, ",
            "yonghuDouble, yonghuDouble1, ",
            "yonghuDouble2, yonghuZong, ",
            "yonghuZong1, yonghuZong2, ",
            "yonghuImg, yonghuImgName, ",
            "yhroleId, yhroleName, ",
            "byuzhiId, byuzhiName, ",
            "byumenId, byumenName, ",
            "byuyuanId, byuyuanName, ",
            "userId, userName, ",
            "bumenId, bumenName, ",
            "buyuanId, buyuanName, ",
            "buzhiId, buzhiName)",
            "values (#{yonghuname,jdbcType=VARCHAR}, #{yonghupassword,jdbcType=VARCHAR}, ",
            "#{yonghuxingming,jdbcType=VARCHAR}, #{yonghusex,jdbcType=INTEGER}, ",
            "#{yonghuage,jdbcType=INTEGER}, #{yonghuphone,jdbcType=VARCHAR}, ",
            "#{yonghuminzu,jdbcType=VARCHAR}, #{yonghumark,jdbcType=VARCHAR}, ",
            "#{yonghumark1,jdbcType=VARCHAR}, #{yonghumark2,jdbcType=VARCHAR}, ",
            "#{yonghumark3,jdbcType=VARCHAR}, #{yonghumark4,jdbcType=VARCHAR}, ",
            "#{yonghudate,jdbcType=TIMESTAMP}, #{yonghudate1,jdbcType=TIMESTAMP}, ",
            "#{yonghudate2,jdbcType=TIMESTAMP}, #{yonghutype,jdbcType=INTEGER}, ",
            "#{yonghutype1,jdbcType=INTEGER}, #{yonghutype2,jdbcType=INTEGER}, ",
            "#{yonghudouble,jdbcType=DOUBLE}, #{yonghudouble1,jdbcType=DOUBLE}, ",
            "#{yonghudouble2,jdbcType=DOUBLE}, #{yonghuzong,jdbcType=INTEGER}, ",
            "#{yonghuzong1,jdbcType=INTEGER}, #{yonghuzong2,jdbcType=INTEGER}, ",
            "#{yonghuimg,jdbcType=VARCHAR}, #{yonghuimgname,jdbcType=VARCHAR}, ",
            "#{yhroleid,jdbcType=INTEGER}, #{yhrolename,jdbcType=VARCHAR}, ",
            "#{byuzhiid,jdbcType=INTEGER}, #{byuzhiname,jdbcType=VARCHAR}, ",
            "#{byumenid,jdbcType=INTEGER}, #{byumenname,jdbcType=VARCHAR}, ",
            "#{byuyuanid,jdbcType=INTEGER}, #{byuyuanname,jdbcType=VARCHAR}, ",
            "#{userid,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
            "#{bumenid,jdbcType=INTEGER}, #{bumenname,jdbcType=VARCHAR}, ",
            "#{buyuanid,jdbcType=INTEGER}, #{buyuanname,jdbcType=VARCHAR}, ",
            "#{buzhiid,jdbcType=INTEGER}, #{buzhiname,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "CALL IDENTITY()", keyProperty = "yonghuid", before = false, resultType = Integer.class)
    int insert(YongHuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int insertSelective(YongHuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<YongHuPojo> selectByExampleWithRowbounds(YongHuPojoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    List<YongHuPojo> selectByExample(YongHuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Select({
            "select",
            "yonghuId, yonghuName, yonghuPassword, yonghuXingming, yonghuSex, yonghuAge, ",
            "yonghuPhone, yonghuMinzu, yonghuMark, yonghuMark1, yonghuMark2, yonghuMark3, ",
            "yonghuMark4, yonghuDate, yonghuDate1, yonghuDate2, yonghuType, yonghuType1, ",
            "yonghuType2, yonghuDouble, yonghuDouble1, yonghuDouble2, yonghuZong, yonghuZong1, ",
            "yonghuZong2, yonghuImg, yonghuImgName, yhroleId, yhroleName, byuzhiId, byuzhiName, ",
            "byumenId, byumenName, byuyuanId, byuyuanName, userId, userName, bumenId, bumenName, ",
            "buyuanId, buyuanName, buzhiId, buzhiName",
            "from t_yonghu",
            "where yonghuId = #{yonghuid,jdbcType=INTEGER}"
    })
    @ResultMap("edu.thn.ciom.dao.YongHuPojoMapper.BaseResultMap")
    YongHuPojo selectByPrimaryKey(Integer yonghuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") YongHuPojo record, @Param("example") YongHuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByExample(@Param("record") YongHuPojo record, @Param("example") YongHuPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    int updateByPrimaryKeySelective(YongHuPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbg.generated Thu May 20 10:15:44 CST 2021
     */
    @Update({
            "update t_yonghu",
            "set yonghuName = #{yonghuname,jdbcType=VARCHAR},",
            "yonghuPassword = #{yonghupassword,jdbcType=VARCHAR},",
            "yonghuXingming = #{yonghuxingming,jdbcType=VARCHAR},",
            "yonghuSex = #{yonghusex,jdbcType=INTEGER},",
            "yonghuAge = #{yonghuage,jdbcType=INTEGER},",
            "yonghuPhone = #{yonghuphone,jdbcType=VARCHAR},",
            "yonghuMinzu = #{yonghuminzu,jdbcType=VARCHAR},",
            "yonghuMark = #{yonghumark,jdbcType=VARCHAR},",
            "yonghuMark1 = #{yonghumark1,jdbcType=VARCHAR},",
            "yonghuMark2 = #{yonghumark2,jdbcType=VARCHAR},",
            "yonghuMark3 = #{yonghumark3,jdbcType=VARCHAR},",
            "yonghuMark4 = #{yonghumark4,jdbcType=VARCHAR},",
            "yonghuDate = #{yonghudate,jdbcType=TIMESTAMP},",
            "yonghuDate1 = #{yonghudate1,jdbcType=TIMESTAMP},",
            "yonghuDate2 = #{yonghudate2,jdbcType=TIMESTAMP},",
            "yonghuType = #{yonghutype,jdbcType=INTEGER},",
            "yonghuType1 = #{yonghutype1,jdbcType=INTEGER},",
            "yonghuType2 = #{yonghutype2,jdbcType=INTEGER},",
            "yonghuDouble = #{yonghudouble,jdbcType=DOUBLE},",
            "yonghuDouble1 = #{yonghudouble1,jdbcType=DOUBLE},",
            "yonghuDouble2 = #{yonghudouble2,jdbcType=DOUBLE},",
            "yonghuZong = #{yonghuzong,jdbcType=INTEGER},",
            "yonghuZong1 = #{yonghuzong1,jdbcType=INTEGER},",
            "yonghuZong2 = #{yonghuzong2,jdbcType=INTEGER},",
            "yonghuImg = #{yonghuimg,jdbcType=VARCHAR},",
            "yonghuImgName = #{yonghuimgname,jdbcType=VARCHAR},",
            "yhroleId = #{yhroleid,jdbcType=INTEGER},",
            "yhroleName = #{yhrolename,jdbcType=VARCHAR},",
            "byuzhiId = #{byuzhiid,jdbcType=INTEGER},",
            "byuzhiName = #{byuzhiname,jdbcType=VARCHAR},",
            "byumenId = #{byumenid,jdbcType=INTEGER},",
            "byumenName = #{byumenname,jdbcType=VARCHAR},",
            "byuyuanId = #{byuyuanid,jdbcType=INTEGER},",
            "byuyuanName = #{byuyuanname,jdbcType=VARCHAR},",
            "userId = #{userid,jdbcType=INTEGER},",
            "userName = #{username,jdbcType=VARCHAR},",
            "bumenId = #{bumenid,jdbcType=INTEGER},",
            "bumenName = #{bumenname,jdbcType=VARCHAR},",
            "buyuanId = #{buyuanid,jdbcType=INTEGER},",
            "buyuanName = #{buyuanname,jdbcType=VARCHAR},",
            "buzhiId = #{buzhiid,jdbcType=INTEGER},",
            "buzhiName = #{buzhiname,jdbcType=VARCHAR}",
            "where yonghuId = #{yonghuid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(YongHuPojo record);
}